### ISSUE TITLE
Arrow code snippets playground

### ISSUE THREAD

**Issue by calvellido** [arrow-kt/arrow#1013]
Our current code snippets in Arrow documentation lacks interactivity and it would be nice if the code in those sections are analyzed/treated by real Kotlin tools in real time.

Adapting JetBrains [Try Kotlin](https://try.kotlinlang.org) and other resources out there, this can be achieved, though some changes are needed to be made on our current docs rendering management.

**Comment by calvellido** [comment]
I have this ready, but I'd like to ask you for feedback on the best way to integrate it with ΛNK. If you fetch the changes in [interactive-snippets](https://github.com/arrow-kt/arrow/tree/jv-1013-interactive-snippets) branch you can have a look at it.

Basically we will have the snippets on _readOnly_ mode by default, and to make one of the snippets editable and runnable it can be made by adding `{: data-executable='true'}` at the top of the coming Kotlin code.

I have made two Either docs snippets _runnable_ to see it in action:

![captura de pantalla de 2018-10-08 19-01-05](https://user-images.githubusercontent.com/7753447/46623024-a01c2a00-cb2c-11e8-8506-6ff174436bf9.png)


The consideration for this is that we need to include proper imports, define data structures used on that code snippet (or not do it if we want the code to fail), and define a main method. A way to not having a bunch of code snippets repeating imports again and again is to use `//sampleStart` and `//sampleEnd` directives:

````
{: data-executable='true'}
```kotlin
import arrow.*
import arrow.core.*

fun main(args: Array<String>) {
//sampleStart
val left: Either<String, Int> = Either.Left("Something went wrong")
//sampleEnd
println(left)
left
}
````

Which would be shown as you see in the `Either.Left` snippet:

![captura de pantalla de 2018-10-08 18-47-51](https://user-images.githubusercontent.com/7753447/46622901-487dbe80-cb2c-11e8-9ef6-1d84baa06182.png)
![captura de pantalla de 2018-10-08 18-48-07](https://user-images.githubusercontent.com/7753447/46622912-4e739f80-cb2c-11e8-9ac0-cada318d7dba.png)
![captura de pantalla de 2018-10-08 18-59-08](https://user-images.githubusercontent.com/7753447/46622919-52072680-cb2c-11e8-861b-10f416d91b98.png)

We can also adapt it to make the code folding button to not be shown, or to be opened by default, etc.

And, even if right now the code is highlighted following _idea_ colours, we can adapt it to go more in line with Arrow's guidelines if we wanted to.

Please share your thoughts and opinions, other than that this is pretty ready 🙂

**Comment by raulraja** [comment]
@calvellido @dominv this is awesome. Kudos! 

This is going to be extremely useful for new users trying out the library.

I think snippets should be expanded and as far as we are concerned in Arrow there is no need for collapsing sections at all since the snippets should be small enough. Having the option to activate collapsing as part of the `{: data-executable='true'}` directive would be ideal in case we had ever longer snippets.

Are the IDEA colors coming from some kind of theme? If there are themes to choose could you share the links to the docs or lib that you are using in the editor so we can see what our options are? We want most likely @israelperezglez to tweak those anyway.

We can take care of integrating the output of `{: data-executable='true'}` or any other similar ones so it works as part of Ank's syntax. Ank would spit out that directive whenever it finds `ank:playground` or something along those lines.

I presume these snippets are coming from the original site try.kotlinlang.org with arrow in the classpath. If that is still the case we should account for a link close to the snippets that allows you to navigate in a new tab to `try.arrow-kt.io` where you can see the tree of all executable snippets. If that is not the case we need to understand what the implementation looks like so we are able to maintain it and see what options are.

Thanks for this awesome job!
