### ISSUE TITLE
Should `Try.raise` have a `Nothing` generic?

### ISSUE THREAD

**Issue by ZakTaccardi** [arrow-kt/arrow#1078]
Problem:

```kotlin
repo.fetchNameOfBank() // returns `Try<String>`
    .map { name: String -> name.capitalize() } // transformation on expected value
    .flatMap { name: String ->
        val isInsured = repo.isBankFdicInsured(name)
        if (isInsured) {
            Try.Success(name)
        } else {
            // I would like to do this, but it doesn't compile due to a type inference failure
            // Try.raise(Exception("Bank is not insured"))
            
            // so I do this, which is more verbose, but it compiles
            Try.raise<String>(Exception("Bank is not insured"))
        }
    }
```

The issue is having to define `Try.raise<String>(exception)` instead of just `Try.raise(exception)`.

```kotlin
// current implementation, that has the type inference issue
fun <A> raise(e: Throwable): Result<A> = Unexpected(e)

// proposed implementation, which would fix the type inference issue
fun raise(e: Throwable): Result<Nothing> = Unexpected(e)
```

I'm sure there's a reason this was designed this way, so changing it now may be too late...but what is that reasoning?

**Comment by pakoito** [comment]
And change error recovery to `recoverWith` #wishlist

**Comment by kartoffelsup** [comment]
Is this still desired? I got the impression there is desire to remove Try from arrow altogether?
p.s. I've also found a bug in the TryTests:
https://github.com/arrow-kt/arrow/blob/master/modules/core/arrow-core-data/src/test/kotlin/arrow/core/TryTest.kt#L62
https://github.com/arrow-kt/arrow/blob/master/modules/core/arrow-core-data/src/test/kotlin/arrow/core/TryTest.kt#L69

These tests never assert anything. And changing 
```kotlin
"combine two Failures should return the second failure" {
      val throwable1 = Exception("foo")
      val throwable2 = Exception("foo")

      Try.raise<String>(throwable2) == Try.raise<String>(throwable1).combine(String.monoid(), Try.raise(throwable2))
}
```
to actually assert with shouldBe, the test fails since the First failure is returned from the combine.

**Comment by pakoito** [comment]
Yikes -.- I'll see if I can take a look this week.
