### ISSUE TITLE
data-executable doesn't work without a newline before the snippet

### ISSUE THREAD

**Issue by pakoito** [arrow-kt/arrow#1130]
I've ninjacommitted 3 fixes to the docs caused by the same pattern, `{:data-executable='true'}` doesn't get applied unless it's unambiguously attached to a block, with an extra line of whitespace.

Example: https://github.com/arrow-kt/arrow/commit/00b6a6336e44ffc034bfa769e01165efef7ed270

**Comment by calvellido** [comment]
This is part of kramdown syntax, and this happens because you can set attributes to a block element setting a block IAL just under or over the desired block, and it seems that when a block IAL is under and also over a block element, the one at the top is the one getting the attribute.

https://kramdown.gettalong.org/syntax.html#block-ials

**Comment by raulraja** [comment]
We are getting rid of playgrounds and the playground server in favor of a dokka plugin that type-checks with ANK. After a few years of having playgrounds, the experience is that it does not get much use, it's costly, and most users would rather have a download file to open in their IDE. Closing this old issue and thanks for all the work 🙏
