### ISSUE TITLE
Type Class Hierarchy Diagrams not shown for typeclasses

### ISSUE THREAD

**Issue by dominv** [arrow-kt/arrow#1177]
Type Class Hierarchy Diagrams not shown for typeclasses, the default error page's code is shown in its place. 
They appear for some other classes as Effects. 

So far, I've checked that the diagram files are being generated and uploaded to the S3 bucket by the **build-and-dokka-transfer** travis stage. They are also downloaded, used to generate the site and finally uploaded by the **deploy-docs** travis task. 
I've checked that they are stored in their respective folders in the S3 bucket.

**Comment by calvellido** [comment]
From what I'm seeing this is due to the recent directories restructure, e.g. `monad.nomnol` file is located in `docs/typeclasses/monad` but the final document will be located at `docs/arrow/typeclasses/monad`, hence the JS script trying to paint the hierarchy but not being able to find the source `nomnol` file.

**Comment by Tylos** [comment]
Let me know what can I do to lend you a hand with this @calvellido !

**Comment by calvellido** [comment]
@raulraja I'm trying to fix this by setting the `nomnol` files to general directories available to be accessed no matter the end path of the page in the end. While I am able to do it when the graph is generated through `outFile` I am not sure how (or if) I can change the path of the file when is done through the macro `ank_macro_hierarchy`, do you think that could that be done?

**Comment by raulraja** [comment]
The actual monad path it's always going to be one and that is what dokka generates. The issue @Tylos worked on is an interim fix as we migrate but at the end of the day the Monad link in the menu just needs to point to the dokka generated markdown that is rendered by jekyll with the default `doc` template. The default doc template always loads the diagram from the current folder.

The ank macro `ank_macro_hierarchy` get's transformed into:
```
kotlin:ank:outFile($packageName-diagram.nomnol)
```
so the relative path is hardcoded and I think it's correct because ultimately we don't want the same page in different links. What we want is that old links are automatically redirected if possible with a Http 301 Permanent Redirect to the new dokka files. At the end of the day if we can't have these redirects it's fine too, we will just loose some traffic to old links but it's not the end of the world.

Can we fix this by simply redirecting anybody landing on `docs/typeclasses/monad` to `dokka/generated/page/url/monad` ? We just need a list of redirects for the menu for links as we migrate them to dokka.

**Comment by calvellido** [comment]
Ok, the point is that the current way of handling proper path based on source structure and redirects is through a mix of the `permalink` setting in markdown files and this Jekyll plugin (https://github.com/jekyll/jekyll-redirect-from). 

The previous directory structure is not changed, so ANK's `outFile` generates a file in, e.g. `/docs/typeclasses/monad/`, but then the Jekyll `build` step through the permalink set will put the final document to `/docs/arrow/typeclasses/monad/`, while keeping a redirect form the previous path thanks to the `jekyll-redirect-from`plugin.

If we want to keep the current way of generating the `nomnol` files in the same place as the document, we need to change the directory structure to be the proper one since the start, and before the `jekyll build` step kicks in.

I can work on that.

**Comment by calvellido** [comment]
This is now fixed :slightly_smiling_face: 

https://arrow-kt.io/docs/arrow/typeclasses/hash/
