### ISSUE TITLE
Dispatchers ambigüity

### ISSUE THREAD

**Issue by JorgeCastilloPrz** [arrow-kt/arrow#1283]
Hi @pakoito , I'm targeting 0.9.0-SNAPSHOT and have this artifacts on my build.gradle:

```groovy
implementation "io.arrow-kt:arrow-core-data:$arrow_version"
    implementation "io.arrow-kt:arrow-effects-io-extensions:$arrow_version"
    implementation "io.arrow-kt:arrow-effects-kotlinx-coroutines:$arrow_version"
    implementation "io.arrow-kt:arrow-effects-kotlinx-coroutines-extensions:$arrow_version"
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-core:$coroutines_version"
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-android:$coroutines_version"
```

I'm getting this issue:

![captura de pantalla 2019-02-04 a las 11 10 07](https://user-images.githubusercontent.com/6547526/52202570-22b0be00-286f-11e9-85f5-ae6ac25914d6.png)

Looks like we have same naming and packaging for both `IO.Companion` extensions. Is that correct ? should I remove some of the dependencies there ?

cc @nomisRev

**Comment by JorgeCastilloPrz** [comment]
Actually, I've tried moving to just:
```groovy
implementation "io.arrow-kt:arrow-core-data:$arrow_version"
    implementation "io.arrow-kt:arrow-effects-io-extensions:$arrow_version"
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-core:$coroutines_version"
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-android:$coroutines_version"
```

And still the problem is there.

**Comment by pakoito** [comment]
The one at the bottom doesn't exist AFAIK, it has one parameter.

**Comment by pakoito** [comment]
The one at the bottom shouldn't exist, there's just one with a single parameter instead: https://github.com/arrow-kt/arrow/blob/master/modules/effects/arrow-effects-extensions/src/main/kotlin/arrow/effects/extensions/io.kt#L145-L147

**Comment by JorgeCastilloPrz** [comment]
So you mean it's wrongly deployed? should that constructor be gone from Arrow?

**Comment by pakoito** [comment]
Try both and see what happens.

**Comment by pakoito** [comment]
Actually, you may have a version in the gradle cache that has both. I had this problem before, IIRC even  forcing to redownload dependencies didn't work because the name is still the same.

**Comment by JorgeCastilloPrz** [comment]
How? Both have the same package name, there's ambigüity on the import. Tried removing all dependencies but looks like both are provided by `arrow-effects-io-extensions` (which transitively depends on `arrow-effects-extensions`)?

**Comment by pakoito** [comment]
>Actually, you may have a version in the gradle cache that has both. I had this problem before, IIRC even forcing to redownload dependencies didn't work because the name is still the same.

Try the --force-dependencies flag (may not be the right name). Else you have to manually go into the gradle cache directory and delete that one yourself.

**Comment by JorgeCastilloPrz** [comment]
Alright. That didn't work either, but Invalidate caches & restart worked. It seems that you were right, I had an older cached snapshot. Interestingly, it was the IDE the one complaining and showing red lines everywhere. It compiled good by command line.

Closing this now. Thanks for your help! 👍

**Comment by soberich** [comment]
@JorgeCastilloPrz For u to know. One is the reasons my team rejects/struggles with adoption of arrow is that IDE support is so-so. Arrow is super hard for IDE. IntelliJ doesn't even show you the option to get hierarchy of classes within arrow. Wrong import messes everything up. Completely! All in red, yellow, etc. You can't see the root cause because of the noise.

Please, consider `idea.ext` plugin for some 
better integration maybe... Maybe create an extention to that plugin of some kind.

**Comment by pakoito** [comment]
I'm confused as Arrow only uses vanilla features, it should be like any other library. Are you sure you're importing the sources too? Are you using any of the code generation?

**Comment by soberich** [comment]
@pakoito I'll work on some demo (at least screenshot), but normally what you have is:
1. By default you don't import sources whether gradle or maven, but so, I don't know how would that be if to make all sources be downloaded by default.
2. Having point 1. in mind, right clicking on any class there is an option to see the inheritance diagram... but not for arrow-kt classes! That's what we experience.

**Comment by soberich** [comment]
> have you done the additional configuration step?
Yes, but to emphasise - I'm saying that IF you've made wrong import (e.g. with same but from different artifact / package, say `fx` from `deferred` instead `concurrent`. But I understand it is on our side. Wrong import is Wrong import...

**Comment by raulraja** [comment]
If KEEP-87 is approved this will be a non-issue since you can achieve the syntax by resolution without imports just based on the types you are using.

**Comment by pakoito** [comment]
>Having point 1. in mind, right clicking on any class there is an option to see the inheritance diagram... but not for arrow-kt classes! That's what we experience.

Is this for interfaces (Functor) or for data classes (Option, Either)?

**Comment by soberich** [comment]
As we started to investigate it turned out that clearly an IntelliJ IDEA treats Arrow in a weird way that you can't quickly get to a class diagram from common right click option.
So if you first go to `Type hierarchy` (`^H`) and that in that window you right click on type and than click to get a class disgram - you get it for whether `data class` or `interface`: 
![image](https://user-images.githubusercontent.com/25544967/56498797-a2ac0300-6503-11e9-9682-799edea15fe7.png)

BUT as I said, option disappears from most useful place, where you commonly get it by right-clicking and going `Diagrams`->`Java class diagram` 
here is `arrow.effects.IO` - a `sealed class`,
![image](https://user-images.githubusercontent.com/25544967/56498383-b7879700-6501-11e9-92ba-6d00550f89bf.png)

Shortcuts also stubbornly do not work, but this is well known (as for us, I can say) that on Macs every now and then some/all shortcuts whether stop working or just don't work forever.

Thank you for your time. There is a room for improvement for such a huge system as IntelliJ IDEA and particularly in case working with Arrow-kt library.

**Comment by pakoito** [comment]
There's a chance it's trying to get the hierarchy of IO's companion object, which doesn't have any.

**Comment by pakoito** [comment]
@soberich someone just pointed out that IJ doesn't support well showing class diagrams in Kotlin altogether: https://www.reddit.com/r/Kotlin/comments/bldit0/kotlin_census_2018/emppjxj/
