### ISSUE TITLE
Possible bug: extension not being generated

### ISSUE THREAD

**Issue by zsmb13** [arrow-kt/arrow#1316]
I'm trying to get something to work with extensions based on an example in the docs:

```
interface Eq<F> {
    fun F.eqv(b: F): Boolean
    fun F.neqv(b: F): Boolean = !eqv(b)
}

data class User(val id: Int) {
    companion object
}

@extension interface UserEq : Eq<User> {
    override fun User.eqv(b: User): Boolean = id == b.id
}
```

Now, I can make the `neqv` call work, as that extension is generated as I'd expect:

```
val user1 = User(1)
val user2 = User(2)

user1.neqv(user2)
```

However, I don't get an `eqv` extension generated. I did get an `eq` extension that I _could_ then open a scope on with `run`, but this isn't very neat:

```
User.eq().run {
    user1.eqv(user2)
}
```

As far as I understand `eqv` should also be generated as an extension, but it isn't.

```
user1.eqv(user2) // right now, unresolved reference: eqv
```

This is on version 0.9.0-SNAPSHOT. Here's a project reproducing this issue: https://github.com/zsmb13/arrow-extension-example

**Comment by pakoito** [comment]
That sounds correct. The reason is that the abstract implementation usually delegates to the member implementation, which is the preferred one to use. Checking whether the typeclass delegates to a member expression etc. is hard to check, so the current approach isn't too bad.

**Comment by zsmb13** [comment]
I'm not sure I understand. Am I supposed to go through `eq` then to be able to call `eqv` on a user?

**Comment by pakoito** [comment]
Hmmmm trying to come up with an example I saw the problem. Okay, it's legitimate.

**Comment by kioba** [comment]
Using the extension function without specifying the object will bind you always to the same object. It's like using a global variable. Implicit helps to find the implementation compile time, but on testing, you might want to switch out the implementation. It can not be done with the extension functions.
I am not even sure if the defaults implementation of the type class is actually safe from this or not.

**Comment by raulraja** [comment]
@kioba Default implementations of type classes are not meant to be overridden as they represent the canonical behavior a type provides without inheritance coupling between behavior in the data type. They should be considered coherent.

If you wish to swap the implementation you can do that by simply defining a new extension in a new package. Instead of depending on the concrete projected extensions functions you may depend on the type class as receiver `MyTypeClass<F>.foo()` providing at concretion your own implementation `IO.myTypeClass.run { foo() }`or the exported functions for the new extension that have been exported in a new package.

The companion factory is also exported in the package alongside the rest of the extensions allowing you to summon different instances. This will change if KEEP-87 is approved and in those cases, you would have to declare your extensions as `internal` in order to override the coherent canonical version provided by Arrow or the data type author.

**Comment by kioba** [comment]
>Default implementations of type classes are not meant to be overridden as they represent the canonical behavior a type provides without inheritance coupling between behavior and the data type. They should be considered coherent.

@raulraja  you are right, this is actually a very nice definition! It helped me to clear out some things 😅. Thank you for this! 

> Instead of depending on the concrete projected extensions functions you may depend on the type class as receiver

So in the example with the User you would suggest to use like this?

```kotlin
fun main() {
  val user1 = User(1)
  val user2 = User(2)
  Eq<User>.run{ user1.eqv(user2) }
}
```

> The companion factory is also exported in the package alongside the rest of the extensions allowing you to summon different instances.

I believe this is the part that I miss and can't really see how to do it yet. I will try to get deeper into a test project.

my problem is around removing side effects from the extentions in test enviroment. Sticking with the User example, lets assume `eqv` implementation has a side effect for example a database query. Testing the following function is not possible if we use the extention function:

```kotlin
fun nonTestableUserEqv() {
  val user1 = User(1)
  val user2 = User(2)
  user1.eqv(user2)
}
```

**Comment by raulraja** [comment]
If you were to mix side effects `Eq` as defined is not a good option. It's meant to be an in-memory object structural comparison for the most part. In Arrow Fx you would model this with suspend functions if you use the latest snapshot or wait for 0.9.0. https://arrow-kt.io/docs/effects/fx/

That is the only way alongside `IO` to do purely functional side effects handling.

Now if you just want to override behaviors for testing purposes and to do that you are ok with bypassing coherence and providing an orphan instance that satisfies your use case you can certainly do so by instead of using the imported coherent extensions define your program so you can selectively inject whatever instances you need. Untested but something along the lines of...

```kotlin
class BizEq<A>(eq: Eq<A>) {
  fun A.bizEqv(other: A) =
    eq.run { eqv(other) }
}
```
```kotlin
package prod

@extension interface ProdUserEq : Eq<User> {
    override fun User.eqv(b: User): Boolean = id == b.id
}
```
```kotlin
package test

@extension interface TestUserEq : Eq<User> {
    override fun User.eqv(b: User): Boolean = TODO()
}
```
```kotlin
import prod.extensions.user.eq.eq
class UserRepo(eq: BizEq<User> = BizEq(User.eq())) : BizEq<User> by eq {
  ... use the syntax to compare users as you wish without `run` since `by` above will delgate syntax
}
```
```kotlin
import test.extensions.user.eq.eq
val testRepo = UserRepo(User.eq())
```
