### ISSUE TITLE
Add peek function to optional

### ISSUE THREAD

**Issue by diegodpf** [arrow-kt/arrow#1361]
I used to use [Vavr](http://www.vavr.io) and I am migrating to Arrow now, so I miss a function that applies an action to the value if the option is defined ([peek](https://static.javadoc.io/io.vavr/vavr/0.9.2/io/vavr/control/Option.html#peek-java.util.function.Consumer-) function in Vavr).

Is there any better way to perform that operation? Or maybe I can raise a PR with something similar with the code below.

```
fun <A>Option<A>.peek(f: (A) -> Unit): Option<A> {
    this.fold(ifEmpty = {}, ifSome = { f(it) })
    return this
}
```

**Comment by pakoito** [comment]
Yes, we have `effectM` in the extensions package! Same stuff: https://github.com/arrow-kt/arrow/blob/master/modules/core/arrow-typeclasses/src/main/kotlin/arrow/typeclasses/Monad.kt#L51

**Comment by raulraja** [comment]
Even if you wrap it, this function it's unsafe because it can only perform side effects and these effects are not suspended. I understand Vavr's design choice because Java has no effect control but Kotlin does through `suspend` or lazy data types like `IO`

It can work when we are in the context of IO if it where defined like this:

```kotlin
fun <A> Option<A>.peek(f: suspend (A) -> Unit): IO<Option<A>> =
  fold({ IO.just(this@peek) }, { IO.delay { f(it) } })
```

In contrast, if you just use `Some(sideEffect())` the effect is still performed which is unsafe and breaks function purity unless it's `suspend` or wrapped in `IO`. This is because `Option`, `Try`, `Either` and friends can't suspend side effects, their constructors are eager and effects run before these data types have a chance to actually wrap the function that performs the effect.

The proper way to express functions that may cause side effects is with `suspend` and `IO`. Programs that wrap side effects outside of suspend or IO are impure and can't be reasoned about in the same way global mutability and state can't be reason about. We have no guarantees that invoking such functions will perform no effects.

This way we do have guarantees that programs are pure:

```kotlin
suspend fun <A> Option<A>.peek(f: suspend (A) -> Unit): Option<A> =
  if (isEmpty()) this else f(t)

val program: IO<Option<A>> = 
  fx {  
    !effect { someOptValue.peek { println(it) } }
  }
```

`peek` is suspended and can only be run in other suspend or inside `fx`
