### ISSUE TITLE
["Request"] convenient Option.mapNotNull

### ISSUE THREAD

**Issue by StefanSchrass** [arrow-kt/arrow#1475]
What version are you currently using?
0.9.0

What would you like to see?
I hope I am not missing out on something, but I would like to have a convenient `Option.mapNotNull`.

What I find myself doing often is 
```
Option.fromNullable(foo)
    .flatMap { Option.fromNullable(it.bar) }
    .flatMap { Option.fromNullable(it.baz) }
```
And what I would love having is something similar to
```
Option.fromNullable(foo)
    .mapNotNull { it.bar }
    .mapNotNull { it.baz }
```
So it kind of prevents `Some(null)` from happening and smartcasts from `T?` to `T`.

**Comment by raulraja** [comment]
@StefanSchrass I feel your pain but I think the best solution is the other way around. We need to add `map`, `flatMap` and essentially any available combinator in Option as extension functions for nullable types for folks that would rather use the classic FP combinators over direct syntax:
```kotlin
fun <A, B> A?.fold(ifEmpty: () -> B, ifFull: (A) -> B): B = 
  this?.let(ifFull) ?: ifEmpty()
fun <A, B> A?.map(f: (A) -> B): B? = 
  this?.let(f)
fun <A, B> A?.flatMap(f: (A) -> B?): B? = 
  this?.let(f)
```
These are just stylistic because as you can observe their implementation body is simpler than the actual function signature. Kotlin has chosen to model 2 effects hardcoded in its type system. Option <-> ? and Effects <-> suspend

If you still want to pursue this I'll help review. Also if you have a more elaborate example that illustrates the pain more than foobar we can maybe suggest a better encoding for your problem.

**Comment by nomisRev** [comment]
@raulraja I think the API @StefanSchrass is looking for is `fun <A, B> Option<A>.flatMap(f: (A) -> B?): Option<B> = flatMap { a -> Option.fromNullable(f(a)) }`, not an `API` for nullable types.

**Comment by raulraja** [comment]
@nomisRev yes but I don't think we should add those to Option so I'm proposing an alternative so that he does not have to put those in Option in the first place if the only thing he is doing is to call `map` on them. That is why I asked for a more elaborate example since the `foo` `bar` does not make sense if all this code is doing is call `map` or `flatMap`.

**Comment by StefanSchrass** [comment]
@raulraja yes indeed my motivation is a stylisitc one and I pretty much had in mind what @nomisRev wrote.

What confuses me a lot is that `Some(null)` is actually possible. I had expected that `map { null }` yields `None`. Surely, in some cases `null` could signal something meaningful, so from this perspective this could be reasonable.
What tried to do was `filter { it != null }` but this does not smartcast into non-nullable types.
I also tried with `Either`, where a `rightIfNotNull` and `leftIfNull` exist.
In `kotlin.collections` is a `mapIfNotNull` what gave me the idea of adding a 
```
fun <A, B> Option<A>.mapIfNotNull(f: (A) -> B?): Option<B> = 
    flatMap { a -> Option.fromNullable(f(a)) }
```
as it would be a convenient shortcut to what I do now with `.flatMap(Option.fromNullable(it.bar))`.

I don't have any examples I could share and also this is not a _special_ problem, more a convenience thing.
Surely I could use the `?.` and `!!` but I hate them with a passion, also because those expressions could get very lengthy what hurts readability a great deal.

**Comment by raulraja** [comment]
@StefanSchrass why don't we try it out in a PR adding those methods to Option and we discuss it there?. We can then see if the new methods impact usage in any way. I have unpopular opinions about `Option` which I discussed last night with @nomisRev. Option is largely useless unless you use polymorphism or typeclasses and then it's very useful because it's a data type and `?` is not. Regarding `null`, yes, null is a value in Arrow if you want to use it as such and this is consistent with other implementations of `Option` like the one in Scala where `Some(null)` does not yield `None`.

**Comment by StefanSchrass** [comment]
@raulraja agreed. I think I can issue a PR this week, maybe today. 
Nothing against unpopular opinions, I personally have a bunch of them.

**Comment by Octogonapus** [comment]
@pakoito Seems like this should be closed.

**Comment by pakoito** [comment]
Yay :D
