### ISSUE TITLE
Behaviour of Optional.asSetter().set vs Optional.set

### ISSUE THREAD

**Issue by rossdanderson** [arrow-kt/arrow#1542]
I'm a bit confused about the behaviour of Optional.asSetter().set() so I've set up the following test:
```
        println(json.stringify(Config.serializer(), config))

        println(json.stringify(Config.serializer(), Config.defaultPort.asSetter().set(config, "ABC")))

        println(json.stringify(Config.serializer(), Config.defaultPort.set(config, "XYZ")))
```

```
{
    "defaultPort": null,
    "minDelayMillis": 50,
    "ledCount": 60,
    "saturationAlpha": 1.5,
    "contrast": 7.0
}
{
    "defaultPort": null,
    "minDelayMillis": 50,
    "ledCount": 60,
    "saturationAlpha": 1.5,
    "contrast": 7.0
}
{
    "defaultPort": "XYZ",
    "minDelayMillis": 50,
    "ledCount": 60,
    "saturationAlpha": 1.5,
    "contrast": 7.0
}
```

I would have thought that in the second case it should have set `defaultPort` to "ABC" in the same way as it sets it to "XYZ" in the third?

Could anyone confirm if my assumption is wrong?

**Comment by nomisRev** [comment]
Hi @rossdanderson,

I just dug into the code and you're correct. Thanks for catching this!

[Optional](https://github.com/arrow-kt/arrow/blob/master/modules/optics/arrow-optics/src/main/kotlin/arrow/optics/Optional.kt#L248) overrides only `modify` of `Setter` and not `set`.
Since `Optional#modify` takes into account if the value is present or not, similar to `Option#map`  the derived `Setter#set` behaves like `modify`.

The correct impl is:

```
fun asSetter(): PSetter<S, T, A, B> = object : PSetter<S, T, A, B> {
  fun modify(s: S, f: (A) -> B): T = this@asSetter.modify(s, f)
  fun set(s: S, b: B): T = this@asSetter.set(s, f)
}
```

If you're interested in testing this and opening a PR that'd be great! Otherwise I'll try to squeeze it into with the next release 👍

**Comment by rossdanderson** [comment]
Thanks, I'll try and have a look at it this evening

**Comment by rossdanderson** [comment]
I've raised this now. One further question I have if you've got a moment, an Optional can focus into and set a property, but cannot unset it as far as I understand. I can see how this makes sense from the Setter's perspective, but would it make sense from the Optional's?
