### ISSUE TITLE
Does the data get processed on my machine or does it get uploaded to the server?

### ISSUE THREAD

**Issue by donkii** [arrow-kt/arrow#1601]
Title

**Comment by pakoito** [comment]
I am...confused

**Comment by MaureenElsberry** [comment]
Hi @donkii - The media issue template should only be used for adding articles or videos to the arrow site... if it's a question, it's best to be asked in the Arrow Gitter channel: https://gitter.im/arrow-kt/Lobby or over at the Arrow channel on Kotlin Slack: https://kotlinlang.slack.com/

Otherwise, we have templates for bugs/suggestions, etc or just open a normal issue.

Thanks!
