### ISSUE TITLE
StackOverflow in SequenceK.filter

### ISSUE THREAD

**Issue by kageru** [arrow-kt/arrow#1815]
Using Arrow’s `SequenceK` and the `filter` extension function seems to filter recursively, which causes a StackOverflow when too many consecutive elements don’t satisfy the predicate.
This does not occur with standard Kotlin sequences.

Example:
```kotlin
import arrow.core.extensions.sequencek.functorFilter.filter
import arrow.core.k

fun main() {
  (1..10000).asSequence().k()
      .filter { it > 5000 }
      .first()
}
```
will result in:
```
Exception in thread "main" java.lang.StackOverflowError
	at arrow.core.SequenceK.iterator(SequenceK.kt)
	at arrow.core.SequenceK.iterator(SequenceK.kt)
	at arrow.core.SequenceK.iterator(SequenceK.kt)
	at arrow.core.SequenceK.iterator(SequenceK.kt)
	at arrow.core.SequenceK.iterator(SequenceK.kt)
	at arrow.core.SequenceK.iterator(SequenceK.kt)
	at arrow.core.SequenceK.iterator(SequenceK.kt)
	at arrow.core.SequenceK.iterator(SequenceK.kt)
        ...
```

Using Kotlin 1.3.60, Arrow 10.3, and openJDK 13.

**Comment by raulraja** [comment]
Thanks @kageru, this is clearly a bug.

**Comment by 1Jajen1** [comment]
So after a bit of digging:
`filter` is implemented using `filterMap` from `FunctorFilter` for `SequenceK`.
`filterMap` is implemented as `map().foldLeft()` and thats where the problem is: `foldLeft` will evaluate the entire sequence, because it's a fold. But especially because it is used as a refold here, this can be avoided by delegating to other methods. So ideally `filterMap` should be `map().filter()` with `filter` from the stdlib. This happens all over the place within `SequenceK` and it's typeclass instances, since I also encounter this quite a bit, I'll do a pass over them and provide overrides for everything that currently evaluates the entire sequence if possible.

**Comment by 1Jajen1** [comment]
For future reference: This turned out to be a bug related to the `plus` operation on sequenes. For example: (pseudocode)
```kotlin
(0..10000).asSequence().fold(emptySequence()) { acc, el -> acc + el }.first()
```
This also fails with the same stackoverflow. As noted above, the filter was implemented with a fold, hence the failure.
