### ISSUE TITLE
Misunderstanding Functional Error Handling doc with monad 

### ISSUE THREAD

**Issue by scorsi** [arrow-kt/arrow#1822]
Hello 👋

I'm a fresh beginner to the "real" FP world in Kotlin and just start using Arrow.
I was looking to the documentation and tried to apply the "monad" part of Functional Error Handling Pattern doc. 

I'm trying to achieve something similar to:
```kotlin
import arrow.core.Either
import arrow.core.Right
import arrow.core.Left
import arrow.core.extensions.either.monad.binding

object Nuke
object Target
object Impacted

sealed class NukeException {
    object SystemOffline : NukeException()
    object RotationNeedsOil : NukeException()
    data class MissedByMeters(val meters: Int) : NukeException()
}

typealias SystemOffline = NukeException.SystemOffline
typealias RotationNeedsOil = NukeException.RotationNeedsOil
typealias MissedByMeters = NukeException.MissedByMeters

fun arm(): Either<SystemOffline, Nuke> = Right(Nuke)
fun aim(): Either<RotationNeedsOil, Target> = Right(Target)
fun launch(target: Target, nuke: Nuke): Either<MissedByMeters, Impacted> = Left(MissedByMeters(5))

fun attackEither(): Either<NukeException, Impacted> =
    fx.monad {
        val (nuke) = arm()
        val (target) = aim()
        val (impact) = launch(target, nuke)
        impact
    }

  
attackEither()
//Left(MissedByMeters(5))
```

But got those errors : 
```
e: /somewhere/src/test.kt: (4, 43): Unresolved reference: binding
e: /somewhere/src/test.kt: (25, 5): Unresolved reference: fx
e: /somewhere/src/test.kt: (26, 22): Destructuring declaration initializer of type Either<SystemOffline /* = NukeException.SystemOffline */, Nuke> must have a 'component1()' function
e: /somewhere/src/test.kt: (27, 24): Destructuring declaration initializer of type Either<RotationNeedsOil /* = NukeException.RotationNeedsOil */, Target> must have a 'component1()' function
e: /somewhere/src/test.kt: (28, 24): Destructuring declaration initializer of type Either<MissedByMeters /* = NukeException.MissedByMeters */, Impacted> must have a 'component1()' function
```

My gradle Arrow deps : 
```groovy
def arrow_version = "0.10.3"
dependencies {
    // ....
    implementation "io.arrow-kt:arrow-core:$arrow_version"
    implementation "io.arrow-kt:arrow-fx:$arrow_version"
    implementation "io.arrow-kt:arrow-optics:$arrow_version"
    implementation "io.arrow-kt:arrow-syntax:$arrow_version"
    kapt "io.arrow-kt:arrow-meta:$arrow_version"
    kapt "io.arrow-kt:arrow-generic:$arrow_version"
}
```

Did I miss something ?

Thanks !

**Comment by 1Jajen1** [comment]
The code looks good :+1: 
The imports confuse me tho: `import arrow.core.extensions.either.monad.binding` I think we removed `binding` a while ago, so it's probably old code from one of the examples...
Either way you need to import the `fx` extension method for `Either`, the ide should be good enough to tell you where it is, since it's generated code I can't look it up quickly...
To prevent ambiguity I usually like to reference `fx` with `monad().fx {...}` so for either it would be `Either.monad<LEFT>().fx { ... }` which for your example is `Either.monad<NukeException>().fx { ... }`

**Comment by scorsi** [comment]
Thanks for your fast comment !

I did as you says.

> Either way you need to import the `fx` extension method for `Either`, the ide should be good enough to tell you where it is, since it's generated code I can't look it up quickly...
> To prevent ambiguity I usually like to reference `fx` with `monad().fx {...}` so for either it would be `Either.monad<LEFT>().fx { ... }` which for your example is `Either.monad<NukeException>().fx { ... }`

I have the following:
```kotlin
fun attackEither(): Either<NukeException, Impacted> =
    Either.monad<NukeException>().fx {
        val (nuke) = arm()
        val (target) = aim()
        val (impact) = launch(target, nuke)
        impact
    }
```
But still got an error:
```
e: /somewhere/src/test.kt: (25, 35): Expression 'fx' of type 'MonadFx<EitherPartialOf<NukeException> /* = Kind<ForEither, NukeException> */>' cannot be invoked as a function. The function 'invoke()' is not found
```
Is something missing ?

I'm really new to the Arrow library and I don't understand everything, it's why I'm trying to execute the examples in the documentations.

**Comment by scorsi** [comment]
Ok... I've imported `arrow.core.extensions.fx` (the IDE didn't proposed to import it) and I changed the code to:
```kotlin
fun attackEither(): Either<NukeException, Impacted> =
    Either.fx {
        val (nuke) = arm()
        val (target) = aim()
        val (impact) = launch(target, nuke)
        impact
    }
```
And it works !

Did we always need to specify the template parameter ? Because the following code didn't work:
```kotlin
fun attackEither() =
    Either.fx {
        val (nuke) = arm()
        val (target) = aim()
        val (impact) = launch(target, nuke)
        impact
    }
```
The compiler is totally lost and didn't achieve to infer the type.

**Comment by 1Jajen1** [comment]
Ah good, getting closer :)
I was wrong, the last part of what you tried is correct: The error you are getting refers to the hack arrow uses to emulate higher kinded types.

Every higher kinded type (like Either) inherits `Kind<For**, A>`. Then you get an unsafe method to cast any `Kind<For**, A>` back to your original type. For `Option` this looks sorta like this:
`class Option<A>() : Kind<ForOption, A>` and the conversion `fun Kind<ForOption, A>.fix(): Option<A>`. Because you cannot create values of type `ForOption` the cast is always safe. This is slightly more involved with multiple type parameters, but the idea is the same. The reason for this is so that we can define methods for `Kind<F, A>` in special ways to improve polymorphism. (Check the functor typeclass for example). `fx.monad {}` is also defined in this general way, so to get back to your concrete value you need to call `fix()` on the result of the comprehension

**Comment by 1Jajen1** [comment]
> Ok... I've imported `arrow.core.extensions.fx` (the IDE didn't proposed to import it) and I changed the code to:
> 
> ```kotlin
> fun attackEither(): Either<NukeException, Impacted> =
>     Either.fx {
>         val (nuke) = arm()
>         val (target) = aim()
>         val (impact) = launch(target, nuke)
>         impact
>     }
> ```
> 
> And it works !
> 
> Did we always need to specify the template parameter ? Because the following code didn't work:
> 
> ```kotlin
> fun attackEither() =
>     Either.fx {
>         val (nuke) = arm()
>         val (target) = aim()
>         val (impact) = launch(target, nuke)
>         impact
>     }
> ```
> 
> The compiler is totally lost and didn't achieve to infer the type.

This is because either has two type-parameters, you generally need to fix all of them except the rightmost one. But as I said above, your previous message already had the correct solution, just missing a `.fix()` at the end :)

**Comment by 1Jajen1** [comment]
This all seems overly complicated in the beginning (I learned most of it through arrow as well) but higher kinded types offer a lot of nice benefits for all the hassle they bring.
Also with the compiler plugin that is soon to be released all of that hassle will be gone and you can write code with good inference and all those benefits easily again

**Comment by scorsi** [comment]
Oh you're right, this code works:
```kotlin
fun attackEither(): Either<NukeException, Impacted> =
    Either.monad<NukeException>().fx.monad {
        val (nuke) = arm()
        val (target) = aim()
        val (impact) = launch(target, nuke)
        impact
    }.fix()
```
But so, what's the difference with :
```kotlin
fun attackEither(): Either<NukeException, Impacted> =
    Either.fx {
        val (nuke) = arm()
        val (target) = aim()
        val (impact) = launch(target, nuke)
        impact
    }
```
I must admit I don't understand the differences : Is it the same under the hood ? Which one is best ? The results are the same.

**Comment by 1Jajen1** [comment]
They are actually the same. The first one is the normal way that works for any monad and the second one is a specialised function for either. (I did not know that existed)

Unless you don't know what monad exactly you are working with, always prefer specialised versions as the compiler is much better at type inference.

If you are interested, the definition of `fx` is just:
```kotlin
fun <L, R> Either.Companion.fx(c: suspend MonadSyntax<EitherPartialOf<L>>.() -> R): Either<L, R> =
  Either.monad<L>().fx.monad(c).fix()
```
So it literally does the same thing, but offers more convenience.

**Comment by scorsi** [comment]
> If you are interested, the definition of `fx` is just:
> 
> ```kotlin
> fun <L, R> Either.Companion.fx(c: suspend MonadSyntax<EitherPartialOf<L>>.() -> R): Either<L, R> =
>   Either.monad<L>().fx.monad(c).fix()
> ```
> 
> So it literally does the same thing, but offers more convenience.
Oh I feel stupid, I didn't think of directly looking to the code source.. ^^

I think I'm understanding this part right now.

I have another question about quite the same thing.
I have this kind of code :
```kotlin
Either.monad<Throwable>().fx.monad {
    val (something) = getSomething()
    val (somethingElse) = getSomethingElse()
    somethingElse.configure(something)
    // do things 
    Unit
}.fix()
```
I just want to use `Either.monad` but without returning values, I just want to get it run or returns errors.
I'm not sure it is the best way to do so... Have you any idea to achieve this more properly ?

**Comment by 1Jajen1** [comment]
> Oh I feel stupid, I didn't think of directly looking to the code source.. ^^

Arrow's source is a bit confusing because extensions and data-definitions currently have to be split (also changes with meta), so it's hard to find stuff when you don't know where to look :sweat_smile: 

> I just want to use Either.monad but without returning values, I just want to get it run or returns errors.
I'm not sure it is the best way to do so... Have you any idea to achieve this more properly ?

I am not quite sure I understand what you mean with "without returning values".

To work in an `Either` comprehension means two things, you can only bind things that return the correct `Either` (with the correct left type) and second, you can do anything you can do in a normal function as well.

Btw "bind" is aliased by component1 and not and is the process of calling `flatMap` in a special way. So in the end a program like this:
```kotlin
fx {
  val (x) = comp()
  val y = test(x).bind()
  val z = !test2(y)
  z
}
```

is roughly equal to:
```kotlin
comp().flatMap { x -> test(x).flatMap { y -> test2(y) } }
```

The real one is slightly different, but that should get the idea. So `fx` is just syntax sugar over `flatMap` which should explain why and how you can `bind` values inside the fx block.

**Comment by scorsi** [comment]
Well I want to make some processing using Either values like so:
```kotlin
fun doImport(order: Order) : Option<Throwable> {
    order.files?.forEach { filename ->
        Either.monad<Throwable>().fx.monad {
            val (csvParser) = getS3Object(filename).flatMap(::createCsvParser)
            val (databaseClient) = createRedshiftClient()
            val errors = mutableListOf<String>()
            batchProcessingCsvFile(csvParser) { records ->
                val (errorsToAdd, valuesToInsert) = parseRecords(records, order.module)
                errors.addAll(errorsToAdd)
                insertValues(databaseClient, valuesToInsert)
            }
            logErrors(errors)
            Unit
        }.fix().also {
            if (it.isLeft()) return (it as Either.Left).a.some()
        }
    }
    return None
}
```
As you see, I'm using `Either.monad<Throwable>().fx.monad` just to auto bind and check `Either` values got by `getS3Object`, `createCsvParser` and `createRedshiftClient`, but the monad returns `Unit` value. I'm just checking if the returning `Either` value is Left and if so, stopping the processing and returning the error as an `Option<Throwable>`.
Is it a correct `FP/Arrow`-way to do so ?

**Comment by 1Jajen1** [comment]
You could skip the unit return and the fold at the end by using some existing methods:
`fx { ... }.fix().swap().toOption()`
`swap` changes left and right to right and left and `toOption` creates an `Option` from any `Right` value and just uses `None` for `Left`.

Btw do you want to stop processing the entire list in case one error happens somewhere? Because then you can use `traverse` instead of `map` and it will short-circuit on the first error. Then follow it with `swap().toOption()` and you have your old behaviour back with added short-circuit behaviour.

> Is it a correct FP/Arrow-way to do so ?

Don't worry about this too much. It mostly depends on opinion and how far you want to take certain concepts. This is a very wide field and I'd suggest incrementally learning and using it, there is really no point in trying to learn about it all upfront and even trying that will likely make code worse because partial knowledge might lead to more harm than good.

So to answer your question from my point of view about fp: No, not really, but for different reasons you might think:

- Using `Either<Throwable, A>` usually means that you are wrapping some code that throws exceptions. In that case that is the same as using `IO<A>` (or `suspend a`) , but you can use some methods of `IO` to automate that wrapping and automate catching those exceptions. You also get several other benefits from `IO` over `Either` in this case. More on that below. As a general rule: `Either` is good at showing failure cases from pure code (functions without side-effects, which include throwing. Also `IO` is pure, even if the code it executes isn't)
- Unit returning always implies side-effects, and guessing what your methods do by their name that is what is happening. I dislike side-effects because those are hard to test and even harder to reason about and refractor. So imo it is always better to explicitly denote code that uses side-effects by using `IO`. As I said above, that grants you automatic error-catching in some methods (in most cases, the IO docs should describe better how this is done). For example there is a fx comprehension on `monadThrow` that should automatically catch. It also grants very strong concurrency primitives on top of that. 

`IO` also has a bunch of error handling methods, one of those being `attempt`, with which you can inspect the result of an `IO` operation (`IO<A>.attempt(): IO<Either<Throwable, A>>`)

So imo this code would be better with `IO` as it better describes what the function is going to do. But as I said above, take it step by step. Using `IO` is a good thing and imo not too hard, but only works if you push the inevitable `unsafeRun` as far to the outside of your program as possible. (Otherwise use `unsafeRunAsync` etc to convert `IO` to a regular `suspend fun` to retain the benefits).

Btw, this is getting a bit off-topic for this issue :see_no_evil: I don't think this is a problem, so feel free to ask as many things as you want on github/here, but most of the community hangs out in the kotlin-lang slack, and specifically in the arrow channels, so you might get responses/ideas etc a lot faster there :)

**Comment by scorsi** [comment]
Oh yes, I see. I changed my code to return `IO<*>` instead of `Either<Throwable, *>` and it works like a charm. I catched all errors in the `IO.fx { /* code */ }`, I also add `.swap().toOption()` as you suggested.

I have so : 
```kotlin
fun doImport(order: Order): List<Option<Throwable>> {
    return (order.files ?: listOf()).map { filename ->
        IO.fx {
            val (csvParser) = getS3Object(filename).flatMap(::createCsvParser)
            val (databaseClient) = createRedshiftClient()
            val errors = mutableListOf<String>()
            batchProcessingCsvFile(csvParser) { records ->
                val (errorsToAdd, valuesToInsert) = parseRecords(records, order.module)
                errors.addAll(errorsToAdd)
                insertValues(databaseClient, valuesToInsert)
            }
            logErrors(errors)
            Unit
        }.attempt().unsafeRunSync().swap().toOption()
    }
}

/// With : 
private fun getS3Object(filename: String) =
    IO {
        AWS.S3.client
            .getObject(GetObjectRequest("some-bucket", filename))!!
    }
/// Instead of :
private fun getS3Object(filename: String) =
    try {
        AWS.S3.client
            .getObject(GetObjectRequest("some-bucket", filename))
            .rightIfNotNull { NullPointerException() }
    } catch (e: Throwable) {
        e.left()
    }
```

The code seems more elegant than before and more "pure".

I think it's still in the topic "Functional Error Handling". :)
I have one more (and last) question : in the `unsafeRunSync()` function doc, it's written `**NOTE** this function is intended for testing, it should never appear in your mainline production code!`. What should I do for "production code" ? Should I run this in a Kotlin Coroutine ?

**Comment by 1Jajen1** [comment]
Usually you'd want to defer running an `IO` with `unsafeRun` as far as possible, which most of the time refers to the entrypoint of your program. Like a main method, or comparable. 

If for whatever reason you have no control over the code up to that point, or don't want to refractor a lot of code, the best solution would be to run the `IO` async in a suspend function. If that's not an option either, just run it like you did above.

In theory `IO` is a type which you cannot escape and thats for good reason: You loose track of side-effects etc when doing so, in practice you also loose cancellation and concurrency benefits `IO` provides. In practice this means, escape it only at the last possible moment (in haskell there is, ignoring unsafe methods, only one such place and that is the main method, in kotlin it's a good to do something similar to not loose the benefits of `IO`).

Regarding `unsafeRunSync`: It's use is blocking, thats why that note is there. It does not matter when you are at the edge of your system (in something like the main method) but in your case it's a better idea to either refractor in a way that you get `IO` to the edge of your system or by running it in a coroutine. Methods like `unsafeRunAsync` etc can help here.

To push `IO` out as far as possible you would have `doImport` return `IO<List<Option<Throwable>>>` and then work with the combinators `IO` provides you. This usually means learning about the different typeclasses `IO` implements to keep the context but still program in an easy and elegant manner. Most notably here are `Functor`, `Monad` and `Traversable` (and the typeclasses they inherit). As usual, if you have questions just go ahead and ask. I view these concepts as not particularly difficult, but they are different from what most people have been tought which frequently causes confusion :sweat_smile: 

Working with these currently requires a mechanical and mental overhead (due to higher-kinded-types `Kind<F, *>` and because you need to pass these typeclasses manually). This will change in the near future! With arrow-meta most of this overhead will be gone and writing programs in this style will be as easy as doing it in languages like scala, if not easier.

**Comment by scorsi** [comment]
Ok, if I understand : if I use `IO`, my main should look like :
```kotlin
fun main(): Unit {
    somethingReturningIO.unsafeRunSync()
}
```
So all the computation is delayed to when the value is really needed ?

I tried to obtain the return type of `doImport` to match `IO<List<Option<Throwable>>>` but I don't succeed to make it work.
The only thing I tried which works is : 
```kotlin
fun doImport(order: Order, appId: AppId): IO<List<Option<Throwable>>> {
    return IO {
        (order.files ?: listOf()).map { filename ->
            IO.fx {
                val (csvParser) = getS3Object(filename).flatMap(::createCsvParser)
                val (databaseClient) = createRedshiftClient()
                val errors = mutableListOf<String>()
                batchProcessingCsvFile(csvParser) { records ->
                    val (errorsToAdd, valuesToInsert) = parseRecords(records, order.module)
                    errors.addAll(errorsToAdd)
                    insertValues(databaseClient, valuesToInsert)
                }
                logErrors(errors)
                Unit
            }.attempt().unsafeRunSync().swap().toOption()
        }
    }
}
```
But I feel uncomfortable with that, `IO.fx` inside the other `IO` seems not to be the correct way to do so. I need to catch all exceptions as `Option<Throwable>` or similar.

I so changed my code but I run away from the FP style : 
```kotlin
fun doImport(order: Order, appId: AppId): IO<List<Option<Throwable>>> {
    return IO.fx {
        (order.files ?: listOf()).map { filename ->
            try {
                val (csvParser) = getS3Object(filename).flatMap(::createCsvParser)
                val (databaseClient) = createRedshiftClient()
                val errors = mutableListOf<String>()
                batchProcessingCsvFile(csvParser) { records ->
                    val (errorsToAdd, valuesToInsert) = parseRecords(records, order.module)
                    errors.addAll(errorsToAdd)
                    println(valuesToInsert)
                    // insertValues(databaseClient, valuesToInsert)
                }
                println(errors)
                // logErrors(errors)
                None
            } catch (t: Throwable) {
                t.some()
            }
        }
    }
}
private fun getOrder(orderId: String) = IO {
    Order.getById(orderId) ?: throw RuntimeException("Order \"${orderId}\" not found")
}.bracketCase(
    release = { order, exitCase ->
        IO.just(
            when (exitCase) {
                is ExitCase.Canceled,
                is ExitCase.Completed -> order.updateStatus(Order.Status.RefusedForErrors)
                is ExitCase.Error -> order.updateStatus(Order.Status.Delivered)
            }
        )
    },
    use = { order -> IO.just(order) }
)

private fun getAppId(appId: String) = IO {
    AppId.getById(appId) ?: throw RuntimeException("AppId \"${appId}\" not found")
}

// directly called from main
private fun handleOrder(orderId: String) = IO.fx {
    val (order) = getOrder(orderId)
    val (appId) = getAppId(order.appId)
    doImport(order, appId)
}.attempt().unsafeRunSync()
    .swap().toOption()
    .map {
        it.printStackTrace()
    }
```
Is it seem good at your eyes ?
I have a lot of difficulties to correctly handle errors... ^^

**Comment by 1Jajen1** [comment]
Ah ok, let's look at this piece by piece:

```kotlin
fun doImport(order: Order, appId: AppId): IO<List<Option<Throwable>>> {
    return IO.fx {
        (order.files ?: listOf()).map { filename ->
            try {
                val (csvParser) = getS3Object(filename).flatMap(::createCsvParser)
                val (databaseClient) = createRedshiftClient()
                val errors = mutableListOf<String>()
                batchProcessingCsvFile(csvParser) { records ->
                    val (errorsToAdd, valuesToInsert) = parseRecords(records, order.module)
                    errors.addAll(errorsToAdd)
                    println(valuesToInsert)
                    // insertValues(databaseClient, valuesToInsert)
                }
                println(errors)
                // logErrors(errors)
                None
            } catch (t: Throwable) {
                t.some()
            }
        }
    }
}
```

This is not really needed and you are right, nesting those fx calls is not good practice. That is what I meant by knowing how `Functor`, `Traverse` etc work :)

Here is your previous code using a **very** useful combinator called `traverse`:
```kotlin
fun doImport(order: Order, appId: AppId): IO<List<Option<Throwable>>> {
    return (order.files ?: listOf()).traverse(IO.applicative()) { filename ->
            IO.fx {
                val (csvParser) = getS3Object(filename).flatMap(::createCsvParser)
                val (databaseClient) = createRedshiftClient()
                val errors = mutableListOf<String>()
                batchProcessingCsvFile(csvParser) { records ->
                    val (errorsToAdd, valuesToInsert) = parseRecords(records, order.module)
                    errors.addAll(errorsToAdd)
                    insertValues(databaseClient, valuesToInsert)
                }
                logErrors(errors)
            }.attempt().map { it.swap().toOption() }
        }
    }
}
```
I also removed the `unsafeRunSync` and switched it out to just `map` over the `IO` to change it's content.

This code is, although it does not look like it, a fold: What happens is, the list gets folded one by one and the accumulator is the `IO`. So in the end you are left with one `IO`, which when run computes all the `IO` actions returned inside `traverse`. More on traverse here: https://arrow-kt.io/docs/apidocs/arrow-core-data/arrow.typeclasses/-traverse/index.html (thats not the nicest docs, but it's something).

This has gone way beyond error handling tho :) `IO` will catch most errors for you as it wraps impure code and thus always expects errors to be thrown. This is acceptable when we are talking about pure code (which we are with `IO` and `IO.attempt`).

To go back to functional error handling: It is not much about where errors are thrown or caught, but who has to handle the error: When you return a `IO` action then the caller knows there might be an error but to use the result he does not have to handle the error explicitly. This is slightly different when you return `Either` or `Option`: Here you force the caller to inspect the result (which you cannot do in `IO`, you can only `bind` there). A good practice in functional error handling is to consider who you want the error to handle: If it's the caller directly use `Either` or similar, if it's some top level handler or similar, use some other type like `IO`.

So in short: Errors you do want handled directly use `Either` and otherwise use something like `IO`. It all depends on where and who do you want to force to handle the error.

To go back to your code: When calling `doImport` (considering the version with traverse I wrote), the `IO` returned will not fail. That is because of `IO.attempt`. Every sub-part of the "large" `IO` that is returned already has it's errors handled (by wrapping it in `Either` and then in `Option`). This means that any method calling `doImport` is forced to handle the error if it wants to act upon the result. Consider mapping over the returned `IO`: You now get access to `List<Option<Throwable>>`, this means the function using this result has to handle the errors which are in this list.

Compare this with the difference if you don't call `IO.attempt()`: Now you have entirely different behaviour because the first element of the list that fails will fail the entire `IO` and the return type will likely be `IO<Unit>`. This means that the function using that result does not have to handle the error (it can, but since it's not in the type it does not have to). You can still handle the thrown error by calling `IO.attempt`, or one of the numerous error handling methods, somewhere else.

Enough for this for now, there are some other small things:
Your bracketCase code looks weird, I think the when clause is not quite right :)
Also in the handleOrder function don't forget to call `bind` on the result of `doImport` otherwise the `IO` won't be applied and run :). 

That being said, this is starting to look good :+1:

**Comment by scorsi** [comment]
Hey ! Sorry for the long delay. Thank you so much for your explanation and code ! I think I have grasped all the subtilities. I have to give a look at the differents typeclasses I guess.

I fixed your code and use `traverse` which works like a charm : 
```kotlin
fun doImport(order: Order, appId: AppId): IO<List<Option<Throwable>>> {
    return (order.files ?: listOf()).k().traverse(IO.applicative()) { filename ->
        IO.fx {
            val (csvParser) = getS3Object(filename).flatMap(::createCsvParser)
            val (databaseClient) = createRedshiftClient()
            val errors = mutableListOf<String>()
            batchProcessingCsvFile(csvParser) { records ->
                val (errorsToAdd, valuesToInsert) = parseRecords(records, order.module)
                errors.addAll(errorsToAdd)
                insertValues(databaseClient, valuesToInsert)
            }
            logErrors(errors)
        }.attempt().map { it.swap().toOption() }
    }.fix()
}

private fun handleOrder(orderId: String) {
    IO.fx {
        val (order) = getOrder(orderId)
        val (appId) = getAppId(order.appId)

        Import.doImport(order, appId).bind().map { it.map { it.printStackTrace() } }
    }.attempt().unsafeRunSync()
        .swap().toOption()
        .map {
            it.printStackTrace()
        }
}
```
I used `.fix()` to change `Kind<ForIO, Kind<ForListK, Option<Throwable>>>` to `IO<Kind<ForListK, Option<Throwable>>>` and I also add `.k()` on the list to obtain `Kind<ForIO, ListK<Option<Throwable>>>` and in addition to `.fix()` everything is working fine... I don't really understand why but it worked 😂 

> Your bracketCase code looks weird, I think the when clause is not quite right :)

Yes... this was a typo lol

> Also in the handleOrder function don't forget to call bind on the result of doImport otherwise the IO won't be applied and run :).

You're right, with the new code, I had to add the `.bind()`. But before the new code, it worked without that.

**Comment by 1Jajen1** [comment]
> I used .fix() to change Kind<ForIO, Kind<ForListK, Option<Throwable>>> to IO<Kind<ForListK, Option<Throwable>>> and I also add .k() on the list to obtain Kind<ForIO, ListK<Option<Throwable>>> and in addition to .fix() everything is working fine... I don't really understand why but it worked :joy:

I am so glad this will all be gone soon. There is currently a compiler plugin development that makes all of this casting unnecessary. 

> I fixed your code and use traverse which works like a charm :

`traverse` is literally a superpower :) 

> > Also in the handleOrder function don't forget to call bind on the result of doImport otherwise the IO won't be applied and run :).

> You're right, with the new code, I had to add the .bind(). But before the new code, it worked without that.

It compiled before but that's because `attempt().unsafeRunSync().swap().toOption().map { it.printStackTrace() }` ignores the result. That means the result which had type `IO<ListK<...>>` never got executed, but the compiler saw nothing wrong :)

**Comment by scorsi** [comment]
> I am so glad this will all be gone soon. There is currently a compiler plugin development that makes all of this casting unnecessary.

I'm a hurry to see it. :)

When the end comes, another question is coming.
I used `bracketCase` to automatically handle the updating status but I figured out that even with thrown errors the exit case called is always `Completed` is it because of the `.attempt()` usage ?

**Comment by nomisRev** [comment]
> I used bracketCase to automatically handle the updating status but I figured out that even with thrown errors the exit case called is always Completed is it because of the .attempt() usage ?

Looking at your snippet you throw the error during the `acquire` step. If an error is thrown during the `acquire` step means the resource was not `acquired`, so the `use` method is never called.
So you should be see that error directly in `attempt`. Is `release` actually triggered?

**Comment by scorsi** [comment]
`release` was triggered but always in the `Completed` exit case. I was certainly misusing `bracketCase`. I so removed that part and handle it manually.

You answered all my questions so nicely and so quickly, awesome ! Thank you very much ! :)

**Comment by dalegaspi** [comment]
FYI.  this is not reflected in the [docs](https://arrow-kt.io/docs/patterns/error_handling/#either) this confused me a lot until i found this thread.
