### ISSUE TITLE
[WEB] Missing MTL part

### ISSUE THREAD

**Issue by PhBastiani** [arrow-kt/arrow#1885]
We cannot access the "Incubator/Datatypes" folder on the new web site

**Comment by calvellido** [comment]
What's the behaviour @PhBastiani ? Is any of the links directing you to a different place?  The dropdown not opening?  Are you seeing some messages in the console when browsing the site?  Could you please share your browser details?

Thanks!

**Comment by PhBastiani** [comment]
The 'Datatypes' link does not appear on the main page (incubator part).

**Comment by AntonioMateoGomez** [comment]
Hi @PhBastiani, are you referring to the list of Arrow incubator on the home page?  If so, it is designed like this by the design and engineering team

**Comment by PhBastiani** [comment]
It's about State, Reader, Kleisli, ...

i.e. datatypes referenced in this folder: '/modules/docs/arrow-docs/docs/docs/arrow-incubator/datatypes'

**Comment by PhBastiani** [comment]
My proposal
1. Add a MTL section
2. Add a incubator readme page (accessible from the icon of the main page)

**Comment by raulraja** [comment]
@PhBastiani sounds good

**Comment by AntonioMateoGomez** [comment]
Hi @PhBastiani I have think about your proposal, and I think we could do the following:

Maybe we can reorder the list according to the order it has in the docs section, and also include two new entries `Other Datatypes` and `Other Type Classes` (since there are Data Types and Type Classes in another section), that would fix your first proposal point that may is a more generic approach.

![Captura de pantalla 2020-01-20 a las 11 20 48](https://user-images.githubusercontent.com/25897490/72722171-fd02ee80-3b7d-11ea-9781-cfd6d79ad3ea.png)

About your second proposal point, I think the incubator readme page that you are refering is already the main incubator link in the home secction: https://arrow-kt.io/docs/aql/intro/ and there are two access points (the incubator logo and the `Arrow Query Language` link).

if you agree we will be happy to make the appropriate changes

**Comment by raulraja** [comment]
I don't believe we should use 'other', MTL needs a section of their own in
the incubator where those are included.
