### ISSUE TITLE
[Bug] Race in fiber raises cancellation exception

### ISSUE THREAD

**Issue by 1Jajen1** [arrow-kt/arrow#1971]
```kotlin
IO.fx {
        dispatchers().io().raceN(timer().sleep(10.seconds).followedBy(effect { println("Hello") }), effect { println("Hello world") })
            .fork().bind().join().bind()
}.suspended()
// => Cancellation exception
```

This however works fine:
```kotlin
IO.fx {
        dispatchers().io().raceN(timer().sleep(10.seconds).followedBy(effect { println("Hello") }), effect { println("Hello world") })
            .bind()
}.suspended()
```

**Comment by aballano** [comment]
This another example also raises the same exception:

```
IO.raceN(IO.never, IO.never, IO.never, just(i))
          .map {
            it.fold(
              ::identity,
              ::identity,
              ::identity,
              ::identity
            )
          }
```

**Comment by nomisRev** [comment]
@aballano it's a problem with how we currently deal with cancelation in the `IORunLoop` since `cb(Left(OnCancel.CancellationException))` will get thrown in some cases. But when that happens within another `IO` that `IO` catches the cancelation exception and fails with that.

Other `IO`s don't rely on `CancelationException`, and we don't have to either.
@pakoito mentioned this was added for KotlinX to be able to cancel `delay`, however` that was before `CoroutineScope` & structured concurrency were introduced in KotlinX so that might not be relevant anymore.

So if we can investigate that as part of the KotlinX cancelation integration efforts than we might be able to fix this easily and remove `CancelationException`.

**Comment by aballano** [comment]
> Other IOs don't rely on CancelationException, and we don't have to either.
@pakoito mentioned this was added for KotlinX to be able to cancel delay, howeverthat was beforeCoroutineScope` & structured concurrency were introduced in KotlinX so that might not be relevant anymore.

AFAIK the cancellation [still seems to be necessary](https://kotlinlang.org/docs/reference/coroutines/cancellation-and-timeouts.html#cancellation-is-cooperative).

**Comment by pakoito** [comment]
The problem is in the raceN implementation, where cancelation errors aren't suppressed correctly because we're effectively launching a new coroutine.

**Comment by aballano** [comment]
Indeed that's the case, I've reimplemented the IO's inner race to be cancellable by default, therefore all raceN calling this one within IO do not fail anymore. But if I remember correctly the Concurrent version of race would still suffer from the same problem, which means that depending on how you declare your IO's fx block you might run into the problem or not (e.g. calling `dispatchers().io().raceN`). I believe we should also add extra tests to verify the purpose of the exception itself.

In any case we can discuss if it makes more sense trying to split the PR into 2, one trying to address the race problem itself + adding extra tests and the other removing the exception if we consider it necessary.

**Comment by pakoito** [comment]
+1 for the split

**Comment by aballano** [comment]
@pakoito there you go! #1986
