### ISSUE TITLE
["Request"] Enable incremental annotation processing for processors

### ISSUE THREAD

**Issue by aballano** [arrow-kt/arrow#2032]
> Incremental annotation processing requested, but support is disabled because the following processors are not incremental: arrow.core.extensions.ExtensionProcessor (NON_INCREMENTAL), arrow.fold.AutoFoldProcessor (NON_INCREMENTAL), arrow.generic.CoproductProcessor (NON_INCREMENTAL), arrow.generic.ProductProcessor (NON_INCREMENTAL), arrow.higherkinds.HigherKindsProcessor (NON_INCREMENTAL), arrow.optics.OpticsProcessor (NON_INCREMENTAL).

* ExtensionProcessor
* AutoFoldProcessor
* CoproductProcessor
* ProductProcessor
* HigherKindsProcessor
* OpticsProcessor

More info: https://docs.gradle.org/nightly/userguide/java_plugin.html#sec:incremental_annotation_processing

> Gradle supports incremental compilation for two common categories of annotation processors: "isolating" and "aggregating".

We should investigate which one should we use. In any case it seems the File api cannot be used, but instead [Filer](https://docs.oracle.com/javase/8/docs/api/javax/annotation/processing/Filer.html)

**Note**: This work might be eclipsed when meta is out and we can replace the annotation processors with it, so I'd advise against doing it if it's too complicated.

**Comment by JorgeCastilloPrz** [comment]
Thanks for opening this issue, imho something like this should have high priority.

**Comment by hadilq** [comment]
I start working on it! However, I noticed, here we use kotlin-poet with version `1.1.0`, but they have supported `writeTo(Filer)` [since](https://square.github.io/kotlinpoet/changelog/#version-120) version `1.2.0`, so I believe to fix this issue we need to update this library first. Its current version is `1.5.0` so anyone has any concern about updating this library?

**Comment by JorgeCastilloPrz** [comment]
I don't think we have any limitations for the bump. We've been putting low attention on processors because most of these features will be moved to compiler plugins with Meta. That said, and given Meta is taking longer than expected we'd be glad to get some help with this in the meantime, in my opinion. I think it's reasonable to bump since newer versions are for sure better adapted for incremental compilation, since that is something most of the libraries that rely on annotation processors have been working on already during the last year.

**Comment by hadilq** [comment]
I've created https://github.com/arrow-kt/arrow-core/pull/144 and https://github.com/arrow-kt/arrow/pull/2154 but they're not building correctly as they're two different PRs!

**Comment by hadilq** [comment]
To solve above issue, I committed
```
compile("com.squareup:kotlinpoet:1.5.0")
```
directly in https://github.com/arrow-kt/arrow-core/pull/144. After merging this PR, we can update https://github.com/arrow-kt/arrow/pull/2154 and merge it. Then we need to create another PR to bring
```
compile("com.squareup:kotlinpoet:$KOTLIN_POET_VERSION")
```
back again! 
lmkwdyt.

**Comment by hadilq** [comment]
I did update the `kotlinpoet` library to use its `writeTo(Filer)` method. It was supper easy to use this method for `CoproductProcessor`. However, beside `ExtensionProcessor`, other processors are not using kotlinpoet at all, such as `AutoFoldProcessor`, `HigherKindsProcessor`, `OpticsProcessor`, `ProductProcessor`. For those cases, we use `writeText` or `printWriter` methods to write in the file, which is not recommended. IMHO we should migrate to generate all kotlin codes by kotlinpoet for every processors. Am I right or do you believe there is a better way?

And finally `ExtensionProcessor` case! It uses kotlinpoet, but still there is a problem! `Filer` is a Java API, and in Java we don't allow to use Java keywords in `packageName`s. But we use `const` in package names! For instance for generating `ConstFunctor` we get the following exception
```
e: [kapt] An exception occurred: javax.annotation.processing.FilerException: Illegal name arrow.core.extensions.const.functor
```
Do anyone has any solution for it? Is changing `packageName`s acceptable?!

**Comment by raulraja** [comment]
Addressed in https://github.com/arrow-kt/arrow-core/pull/153 thanks @hadilq!
