### ISSUE TITLE
["Request"] Companion unit objects

### ISSUE THREAD

**Issue by Hiosdra** [arrow-kt/arrow#2134]
What version are you currently using? 0.11.0-SNAPSHOT
What would you like to see?
Hi, in my work, we are using Scala + Cats and for many types, we have very useful`.unit` extension function. What would you say about adding them to arrow as companion functions?
(I can do this 😉)

I mean to add:
```kotlin
val IO.Companion.unit = IO.just(Unit)
val Either.Companion.unit = Either.right(Unit)
```
Probably the same will be for:
1) MonoK & FluxK
2) ObservableK & SingleK & other rx-java wrappers
3) Any other?
4) Try? (I know it is deprecated, so question mark)

**Comment by nomisRev** [comment]
If you're up for it then we should add it to `Either` and Reactor/RxJava and we should also replace the current `just(Unit)` usages for the new cached value as well as the `unit()` function in `Applicative`.

`IO` already has `IO.unit` & we shouldn't do it for`Try` since it should be removed in `0.11.0`.

**Comment by Hiosdra** [comment]
For record: 
Thank you
I didn't forgot about this, only other PR https://github.com/arrow-kt/arrow-integrations/pull/28 is more important for me at the moment. I will do this after ;)

**Comment by raulraja** [comment]
Hi @Hiosdra, speaking with others around the use of `Companion.unit` as a way to construct a value of `F(Unit)` we concluded that `unit`, `just`, and other names made no sense since people use Arrow with concrete types. They always know which constructor to call passing as value Unit. For that reason and others related to naming, we decided to remove all those functions from Arrow and leave `Companion.unit` as internal for edge cases where it's useful. Still, it's not necessarily an idiom we want to promote in 1.0, but If you feel strongly about having these, please reopen this issue, and we can look into it again. Thanks!
