### ISSUE TITLE
Docs generation error - "ERROR CLASS"

### ISSUE THREAD

**Issue by lgtout** [arrow-kt/arrow#2144]
There appears to be a problem with doc generation:

![Λrrow_Core](https://user-images.githubusercontent.com/364799/82264928-b0a4a100-991a-11ea-9542-171e643896bf.gif)

https://arrow-kt.io/docs/0.10/apidocs/arrow-core-data/arrow.core/-either/tail-rec-m.html

The solution may be what @raulraja recommends in this Slack thread: https://kotlinlang.slack.com/archives/C5UPMM0A0/p1589832322364900

**Comment by hadilq** [comment]
Hi! I can take this task

**Comment by rachelcarmena** [comment]
> Hi! I can take this task

Thanks @hadilq :raised_hands: I was reviewing it as well because I was worried about the last changes. It seems the solution is building the project before running dokka and adding a classpath to the dokka configuration.

Let's try it!

**Comment by rachelcarmena** [comment]
Solved for the `next` version: https://arrow-kt.io/docs/next/apidocs/arrow-core-data/arrow.core/-either/tail-rec-m.html

I don't close the issue because it will be fixed for latest release as well in next days.

Other examples of `ERROR CLASS` in latest release that are solved in `next` version:

* https://arrow-kt.io/docs/0.10/apidocs/arrow-ui-data/arrow.ui/-day/index.html
* https://arrow-kt.io/docs/0.10/apidocs/arrow-free-data/arrow.free/index.html
* https://arrow-kt.io/docs/0.10/apidocs/arrow-core-data/arrow.core/index.html
* https://arrow-kt.io/docs/0.10/apidocs/arrow-core-data/arrow.core/-try/index.html
* https://arrow-kt.io/docs/0.10/apidocs/arrow-fx/arrow.fx.extensions/index.html

**Comment by rachelcarmena** [comment]
Thanks for creating this issue @lgtout :raised_hands: 

It's already fixed in both the latest release and the next version.
