### ISSUE TITLE
["Request"] more descriptive naming

### ISSUE THREAD

**Issue by Ahmed-Adel-Ismail** [arrow-kt/arrow#2168]
What version are you currently using?
None

What would you like to see?
We are not able to use Arrow in our company, the main rejection comes from naming, it's functions and class names ambiguity makes it very hard to teach for new joiners ... Please provide more descriptive names (or at least names that we can communicate between each other)

Thanks

**Comment by nomisRev** [comment]
@Ahmed-Adel-Ismail we're currently in the process of simplifying some the patterns/names.

Some related tickets:
 - https://github.com/arrow-kt/arrow-core/issues/115
 - https://github.com/arrow-kt/arrow-core/issues/159
 - https://github.com/arrow-kt/arrow-core/issues/120
 - https://github.com/arrow-kt/arrow-core/issues/114

We try to keep a balance between naming from Kotlin's standard library and functional programming.
If a function known from FP exists in Kotlin's standard library we will always prefer that name starting from Arrow 0.11.0. Which is currently being finished.

Would that solve your problems? Or could you give more concrete examples?

It's difficult to find names that work for everyone since people from different backgrounds have different preferences.

**Comment by Ahmed-Adel-Ismail** [comment]
I think so, what I mean is that function names like fx() or ev(), and types like Eq for example, if you are already working on those names then great

**Comment by raulraja** [comment]
@Ahmed-Adel-Ismail closing this as those functions no longer exist and Arrow has already gone through a major naming overhaul in the last few releases. Feel free to open new issues for any other specific concerns about concrete functions that may have poor naming and can be discussed in isolation. Thanks!
