### ISSUE TITLE
["Request"] Remove arrow-integrations from CI build

### ISSUE THREAD

**Issue by nomisRev** [arrow-kt/arrow#2196]
As discussed in https://github.com/arrow-kt/arrow-core/pull/195#issuecomment-672893490 we're going to disable this repo from the Arrow CI Integration Build.

And the important code should be moved to Arrow Core. https://github.com/arrow-kt/arrow-core/issues/209

**Comment by rachelcarmena** [comment]
Done!! So the arrow-integrations libraries won't be published anymore until it's included again (because no guarantee to keep them working with the rest of libraries).

`arrow-core-retrofit` already exists in `arrow-core` with the promoted features and keeping the Git history. Besides [this pull request removes it from `arrow-integrations`](https://github.com/arrow-kt/arrow-integrations/pull/39)

**Comment by rachelcarmena** [comment]
Reverted!! And https://github.com/arrow-kt/arrow-integrations/pull/39 just removes the consideration of `arrow-integrations-jackson-module` until it's adapted.
