### ISSUE TITLE
["Request"] Monad comprehensions without coroutines

### ISSUE THREAD

**Issue by fcoutinho-uolinc** [arrow-kt/arrow#2378]
What version are you currently using?
0.11.0

What would you like to see?
I would like to be able to use the new **either** {...} syntax without the need to make a suspend function
Kind of the same thing as asked [here](https://github.com/arrow-kt/arrow-core/issues/12)

**Comment by nomisRev** [comment]
Hey @fcoutinho-uolinc,

This is possible already by using `either.eager { }` instead of `either { }`.
Sadly, one of the two functions had to have a different name due to signature clashes.

Reference to [`either.eager`](https://github.com/arrow-kt/arrow/blob/1d2771f057d398115823e882e066b8c654a68711/arrow-libs/core/arrow-core/src/main/kotlin/arrow/core/computations/either.kt#L30)
