### ISSUE TITLE
Kind deprecated in v0.13.0

### ISSUE THREAD

**Issue by rackdon** [arrow-kt/arrow#2401]
After update the version to 0.12.1, I've received the following warn message:
`'Kind<out F, out A>' is deprecated. Higher Kinded types and their related type classes will no longer be supported after Arrow 0.13.0. Most relevant APIs are now concrete over the data types available as members or top level extension functions`, 
and after that I've a doubt.
How could we implement generic interfaces whose methods return T<xxx> if we don't specify T in the interface delaration but in the implementation? 
I mean, actually I create the interface like
```
interface FooInterface<T> {
   fun findAll(): Kind<T, Foo>
}
```
and the implementation
```
class FooImpl(): FooInterface<EitherPartialOf<Throwable>> {
   override findAll(): Either<Throwable, Foo> {}
}
```
There will be any method to maintain the same structure/logic of my current code?

Thank you in advance

**Comment by raulraja** [comment]
Hi @rackdon, 

Kinded polymorphism is no longer supported.

Your code currently would be
```kotlin
interface FooInterface {
  suspend fun findAll(): Foo
}

class FooImpl: FooInterface {
  override suspend fun findAll(): Foo = TODO()
}
```
Or same as above but returning Either<Throwable, A>.
For this case having Throwable in the left of Either is unnecessary because the suspend continuation already implies the possibility of a Throwable. In fact, it always results in a type `Result<Foo>` internally before returning Foo, which is the same as `Either<Throwable, Foo>.`

Do you have a use case where you have more than one implementation for this interface`?

**Comment by rackdon** [comment]
Hi,

I don't have more than one implementation at this moment, but I was open to that possibility in the future. My question was if you will have a similar method in the future version or I have to forget the use of this kind of interfaces

**Comment by raulraja** [comment]
@rackdon We discussed this internally and until FIR is out and stable and we have a stable API for compiler plugins we don't plan on revisiting kinds. We will try again then. Please swing by the kotlin slack at slack.kotlinlang.org if you are not already there and if you want to stay up to date with the latest or continue this discussion there. Thanks!
