### ISSUE TITLE
Explore Gradle Parallel Builds

### ISSUE THREAD

**Issue by pablisco** [arrow-kt/arrow#2446]
Now that we have KMP support for JS and we have multiple builds for different JVM environments, we should explore running different builds in parallel to speed up build times on the CI.

Our thinking is to create a separate builds for each of the following tasks:
- jsLegacyTest
- jsIRTest
- ktlintCheck
- animalsnifferTest

I think this is all we need from `build`. One potential downside with this parallelization is that we would not take advantage of the compile cache between the different jobs. i.e. we need to compile all the code on each job. Compounded the time is more, but in the overall time should be shorter.

Depending on the size we could consider sharing a build cache across jobs, after an initial compiler run.

**Comment by rachelcarmena** [comment]
Great, good idea!! :clap: 

Please, just a warning:

* [This property](https://github.com/arrow-kt/arrow/blob/0.13.2/arrow-libs/gradle.properties#L60) is disabled when releasing because it impacts on the **staging repository creation**. If it's enabled, several staging repositories are created and it's not possible to find a single staging repository with all the artifacts to be released.

It's only detected when releasing (it doesn't happen when publishing SNAPSHOT versions where staging repositories aren't created).

**Comment by rachelcarmena** [comment]
Please, find the details about the release process in [RELEASE.md](/arrow-kt/arrow/blob/main/RELEASE.md).

**Comment by pablisco** [comment]
Thanks for the heads up 🙂  This is about creating parallel GH Action Jobs so, hopefully it shouldn't affect the Gradle setup 🤞

**Comment by rachelcarmena** [comment]
You're welcome @pablisco :raised_hands: In that case, I think it would be necessary to move macOS GH environments to Ubuntu because of the current limit of 5 jobs at the same time. It can be checked now with every pull request: `Verify JDK compilation` has 4 jobs so one of them stays queued while `Build libraries` and `Build documentation` are running.
