### ISSUE TITLE
["Request"] Support KSP for Optics

### ISSUE THREAD

**Issue by ScottPierce** [arrow-kt/arrow#2587]
Currently Optics uses KAPT to generate the optics. It'd be great to see this ported to KSP so that 1. It generates faster, and 2. It's multiplatform.

**Comment by nomisRev** [comment]
Hey @ScottPierce,
Thanks for the issue report! The plugin has been already ported to Arrow Meta and we're in the process of adding it to Arrow atm. You can track the progress here, it'll be released soon.

You can already try the snapshot version as it's defined here.
https://github.com/arrow-kt/arrow/pull/2586 It's failing in the PR due to a circular dependency we have to fix because the plugin automatically applies the Arrow Optics dependency.

**Comment by ScottPierce** [comment]
Awesome! I'll track this there then. Thanks!
