### ISSUE TITLE
["Request"] Remove superfluous type parameter from Resource#tap

### ISSUE THREAD

**Issue by 404-** [arrow-kt/arrow#2635]
What version are you currently using? 1.0.1

What would you like to see? Removal of (seemingly) unnecessary type parameter `B`

Current function signature of `Resource#tap`:

```
fun <B> tap(f: suspend (A) -> Unit): Resource<A>
```

Does `B` serve an actual purpose?

**Comment by nomisRev** [comment]
No, it does not. A PR to remove it would be very welcome!

**Comment by 404-** [comment]
My main worry is that this would be a breaking, non-backwards compatible change. I.e., if right now, when I use `tap`, I'm forced to write something like `resource.tap<Nothing> { ... }` then removing the type parameter would cause a compile-time build error.

So, even though the fix itself is simple, introducing it in any 1.x version seems problematic. Does it mean this change would ship only in 2.x? Or am I missing something?

**Comment by nomisRev** [comment]
I think this can be introduced without a breaking change by using `@Deprecated(level= DeprecationLevel,HIDDEN)`.

The problematic part still is that it still breaks the Kotlin API. `tap<Nothing>` would not fail to compile, and it would tell you there is no `<Nothing>` expected but the `binary` will be backward compatible.

I'm wondering if that is good enough since it will remain binary compatible but upgrading to the newer version would force you to remove the redundant type param.

**Comment by nomisRev** [comment]
@404- what do you think? Breaking the Kotlin API for `resource.tap<Nothing> { ... }` seems a minor issue, if we can do it without breaking the binary.
