### ISSUE TITLE
Question / Suggestion

### ISSUE THREAD

**Issue by 1gravity** [arrow-kt/arrow#2641]
I'm new to FP in general and to this great library specifically so allow me to ask a maybe stupid question.

The `flatMap` function for `Either` allows to bind functions like so (from the official documentation):
```
speaker
    .getTalk()
    .flatMap { it.getConference() }
    .flatMap { it.getCity() }
```

If `flatMap` binds functions together, why isn't it called bind and why doesn't it use lambdas with receivers? By defining a bind function like this:
```
/**
 * Binds the given function across [Right].
 *
 * @param f The function to bind across [Right].
 */
inline fun <A, B, C> Either<A, B>.bind(f: B.() -> Either<A, C>): Either<A, C> =
    when (this) {
        is Right -> f(this.value)
        is Either.Left -> this
    }
```
above example would become more concise and more aligned with official FP jargon imo:
```
speaker
    .getTalk()
    .bind { getConference() }
    .bind { getCity() }
```
Also the term `flatMap` is usually meant to indicate that a datastructure (e.g. an array of arrays) is flattened first before each element is mapped, something that clearly doesn't happen here.

**Comment by raulraja** [comment]
Hi @1gravity, and welcome to Arrow!

You proposed a different encoding for `flatMap` with a receiver which I think it's good and probably more ergonomic than the current `flatMap`. 

`flatMap` is used because other langs like kotlin scala and many java libs refer to `F<A> -> A -> F<B> -> F<B>` with this name. This is also called in other places `Monad bind`. 

We have a `bind` operation for arrow which in a system like kotlin based on delimited continuations allows us to instead of providing a function passing style do it also like `F<A> -> A`. This is available for Either and other data types and if applied to this example it may look like:

```kotlin
either<CustomError> { // if any of the cases below short-circuits with Left
   val talk = getTalk().bind()
   val conf = getConf().bind()
   val city = getCity().bind()
   .....
}
```
`bind` is here available through the Either Effect receiver DSL.

**Comment by 1gravity** [comment]
@raulraja thanks for getting back to me and explaining the use of `flatMap` over `bind`. 
If you consider using receivers for `flatMap` you could also consider using an infix notation which would make it possible to write
```
speaker.getTalk() then Talk::getConference then Conference::getCity
```
which would be close to the `>>=` notation, you could even make it
```
speaker.getTalk() `>>=` Talk::getConference `>>=` Conference::getCity
```
;-)

**Comment by nomisRev** [comment]
Hey @1gravity,

We have considered many different kinds of syntax, but we've recently had to dial back the amount of syntax/APIs we can provide out of the box without bloating the library binary.

The `bind`/`computation` DSLs seem to most idiomatic solution in Kotlin, since it allows removing many patterns from FP by simpler idioms. For example, the need for `Traverse` disappears for most types.

```kotlin
either<Error, List<A>> {
   (1..100).map { either().bind() }
}
```

Closing this issue, feel free to discuss further here or to open a new ticket if you want to propose new APIs.
