### ISSUE TITLE
["Bug"]Unresolved reference using Arrow Optics with KSP for simple example

### ISSUE THREAD

**Issue by mingchuno** [arrow-kt/arrow#2646]
Trying to use Arrow Optics with KSP in my project but it fail to compile even for simple example. I have created a simple reproducer: https://github.com/mingchuno/arrow-optics-ksp-issue-reproducer

When using `1.0.2-alpha.28`, `kspKotlin` task success but nothing is generated under `build/generated/ksp/main`. It will show `Unresolved reference: name` when running `./gradlew assemble`. Switching to `1.0.1` will show `Could not find io.arrow-kt:arrow-optics-ksp-plugin:1.0.1.` instead.

<img width="1278" alt="Screenshot 2022-01-17 at 23 29 23" src="https://user-images.githubusercontent.com/5472190/149797713-e4dd9b96-dce6-4281-88b5-320b4fe13af1.png">

Related issue: #2619

**Comment by serras** [comment]
@mingchuno thanks for reporting this! We are working on a fix in #2649

**Comment by mingchuno** [comment]
@serras Please ping me if you have a snapshot version. I can try it out in my repo.

**Comment by serras** [comment]
@mingchuno you should be able to try it with version `1.0.2-alpha.43`

**Comment by mingchuno** [comment]
<img width="822" alt="Screenshot 2022-01-25 at 09 37 49" src="https://user-images.githubusercontent.com/5472190/150894536-7ad7699c-72fc-4002-a1d4-675cdf9d765d.png">

I can run it but IDE fail to work with it out of the box

**Comment by NorbertSandor** [comment]
@mingchuno, as I see, you don't have applied this Gradle config: https://kotlinlang.org/docs/ksp-quickstart.html#make-ide-aware-of-generated-code

**Comment by mingchuno** [comment]
Thx, it work now. @NorbertSandor https://github.com/mingchuno/arrow-optics-ksp-issue-reproducer

**Comment by nomisRev** [comment]
Thanks @NorbertSandor for letting know. We should clarify, and update the documentation to refect this properly.

**Comment by kfh** [comment]
I've just got hit by this myself and in _contrary_ to what @mingchuno experienced i still had _issues_ after upgrading to version _1.0.2-alpha.43_. After a litt digging i've found that if your _data classes_ contains more than 3 constructor parameters you will get _Unresolved reference_ errors. Look at the following snippets:

```
@optics
data class Foo(val foo: String, val bar: String, val baz: String) {
    companion object
}
```

...compiles and runs without any issues. But the following:

```
@optics
data class Foo(val foo: String, val bar: String, val baz: String, val boo: String) {
    companion object
}
```

..will lead to:

```
Unresolved reference: a
Unresolved reference: b
Unresolved reference: c
Unresolved reference: d
```

The same yields for all constructors that takes more than 3 parameters.

I've poked into the generated code and for the data classes that fails we can see the following:

```
reverseGet = { tuple: arrow.core.Tuple4<kotlin.String, kotlin.String, kotlin.String, kotlin.String> -> 
                                       mypackage.Foo(tuple.a, tuple.b, tuple.c, tuple.d) 
                        }
```

These _tuple values_ should probably be _first_, _second_, _third_ and _fourth_ instead of the _unresolved a_, _b_, _c_ and _d_.

@NorbertSandor @nomisRev thoughts?

**Comment by serras** [comment]
Could you try `1.0.3-alpha.1`? That should be the first one containing the appropriate fix.

**Comment by kfh** [comment]
> 1.0.3-alpha.1

Great. That works :)
