### ISSUE TITLE
[Either] Problem with flatmap and mockito

### ISSUE THREAD

**Issue by eglogis** [arrow-kt/arrow#2680]
Hi! I have a problem doing a test with the map function and a mock data with mockito.

I have this function: 
![image](https://user-images.githubusercontent.com/45403730/157209923-2e222ed5-037e-40c5-b264-bdb6b7065662.png)

and this is their test:
![image](https://user-images.githubusercontent.com/45403730/157210158-aad00abf-511a-412e-a8a2-4c2e666b59d5.png)
 
and this test, throw this error:
![image](https://user-images.githubusercontent.com/45403730/157210328-e6b7823d-924e-4ab1-b863-d998a655073c.png)

I hope you can help me. Thank you!

**Comment by pakoito** [comment]
First things first, Visca Barça! Mockito is both very heavy handed and very lax when mocking, are you sure it isn't reimplementing some of the Arrow internals? Have you considered using regular constructor injection instead?

Otherwise I'd ask directly on the mockito repo because the error doesn't seem to relate to Arrow internals.

**Comment by eglogis** [comment]
I have just solved the problem! The problem is that the function I am mocking is suspend and after a lot of searching, I found the coEvery function and implemented it as follows:
![image](https://user-images.githubusercontent.com/45403730/157234632-8741ea69-96e9-41a9-85dc-a9d7d3c12605.png)
Thank you very much and... Ala Madrid!
