### ISSUE TITLE
Why is 1.1.2 available as a dependency, but no info can be found here or on arrow-kt.io sites?

### ISSUE THREAD

**Issue by Zordid** [arrow-kt/arrow#2713]
What version are you currently using?
1.0.1

What would you like to see?
I see that 1.1.2 is available through my IDE, but nowhere I can find any valid info about this new release. How can that be? Here on GitHub, the latest release is still 1.0.1 from December 2021 and on arrow-kt.io it is the same.

This happened exactly the same before. What am I doing wrong? Where can I find reliable info on new releases as soon as they are popping up on Maven Central? Thanks!

**Comment by hoc081098** [comment]
Same 😂

**Comment by nomisRev** [comment]
Hey @Zordid, @hoc081098,

We've been dealing with some issues in Gradle Publishing, and Github Actions which are out of the expertise of all the current maintainers :(

We've finally solved all known issues with publishing in Gradle, but we now accidentally released `1.1.0` and `1.1.2` to MavenCentral directly. It was supposed to stay in Sonatype so we could sync up the announcement with the actual release.

The official announcement will follow very soon, but we're still trying to put our heads together to try and figure out how those releases made it straight to Maven Central without manual approval.

Sorry for the inconvenience, since nothing is breaking in these releases it's safe to bump to `1.1.2` without the official announcement, which will follow asap. I will keep this ticket open until then.
