### ISSUE TITLE
["Request"] Replace std kotlin libraries 'api' dependency for 'implementation'

### ISSUE THREAD

**Issue by corlaez** [arrow-kt/arrow#2720]
What version are you currently using?
arrow-core 1.1.2

What would you like to see?
I would like arrow to behave as a regular library and use `implementation` for kotlin std libraries (instead of `api`). Right now it uses api which causes the following

![image](https://user-images.githubusercontent.com/18663098/167926681-9815be1e-d41b-4ac8-b2e1-6de76fae1d2b.png)

(While this example shows different minor versions note that if you want to avoid duplication of different std libraries you would have to ensure that your project' kotlin version matches an arrow version with the same kotlin language, down to patch 💥)

A little research showed the moment implementation was changed for api: https://github.com/arrow-kt/arrow/pull/2599 It makes reference to arrow exposing std api types and cites, citing that as the reason for the change. I am not familiar enough with arrow to say whether that's true or not today in arrow core.

**Comment by nomisRev** [comment]
Heu @corlaez,

Thank you a lot for this ticket! For the longest time we used to have it as `compileOnly` when Arrow as a JVM only project, and afaik on the JVM that is a commonly used option and not really frowned upon for libraries such as the Kotlin Std which _shouldn't_ be breaking.

However with Kotlin MPP we first switched to `implementation` and then to `api` because otherwise users can run into the scenario that if their Kotlin version is behind on Arrow it can crash the program. This it not preventable from Gradle afaik.

Do you think it's preferred to opt for `implementation` for a library? I see many Kotlin MPP project taking the approach of using `api` 🤔 It both seems to come with a trade-off.

**Comment by nomisRev** [comment]
> or should I not worry about the duplicated libraries at all?

I think you should not be concerned about this at all. In the JVM it's quite common to have multiple versions of the same versions on the classpath. I've seen this a lot with ReactiveX as well for example.

**Comment by corlaez** [comment]
Got it! I think I can close it then.
