### ISSUE TITLE
["Request"] Publish legacy artifacts for Kotlin/JS

### ISSUE THREAD

**Issue by Kernald** [arrow-kt/arrow#2785]
What version are you currently using? 1.1.2

What would you like to see?

Right now, only klib (IR representation) artifacts are published for Kotlin/JS artifacts (e.g. https://repo1.maven.org/maven2/io/arrow-kt/arrow-core-js/1.1.2/). The IR back-end is still in beta, and as far as I can tell from a quick glance, there's nothing preventing the legacy back-end to be used. It would be nice publishing artifacts for non-IR projects.

**Comment by nomisRev** [comment]
Hey @Kernald,

Currently our biggest blocker for publish `BOTH` is that we cannot run tests for the legacy JS target.
I am personally not using Kotlin JS a lot, but I saw earlier this week that other libraries in the Kotlin MPP eco-system are dropping support for `Legacy JS`. I.e. https://github.com/cashapp/turbine/releases/tag/0.9.0

But of course this is also a testing library... 🤔
Do you know if there is any ETA for JS IR to become stable?
I think it should not be too hard to also publish `Legacy JS`, but we've never gotten a request for this since the introduction of Kotlin MPP in `1.0.0`.

**Comment by Kernald** [comment]
Thanks for the quick reply!

I don't have any idea about the timeline for IR to become stable for Kotlin/JS. I suspect most consumers are happily using IR already - the reason I kind of need that for now is that I'm using Bazel, which at the moment doesn't support JS/IR (https://github.com/bazelbuild/rules_kotlin/issues/808). I was hoping unblocking this on the Arrow side might be easier for now - even though the long term fix is obviously adding support for that in Bazel.

I understand it's definitely not an effort that warrants putting lots of resources behind, feel free to close as unfeasible if testing on the legacy back-end isn't an easy thing to do!

**Comment by serras** [comment]
Kotlin 1.8 [has removed the old backend](https://kotlinlang.org/docs/whatsnew18.html#removal-of-the-old-backend). Should we close this?
