### ISSUE TITLE
["Request"] Improve Iterable extension impl

### ISSUE THREAD

**Issue by raulraja** [arrow-kt/arrow#2812]
Some of our Iterable extensions, such as `partitionEither` have non-optimal implementations that can be easily fixed to produce fewer allocations and iterations.

https://github.com/arrow-kt/arrow/blob/6aa1875a687fb2c1c0e639bdd73be4a05bdfbf7a/arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/Iterable.kt#L1002

Discussion with Mitchell Cohen from slack regarding `partitionEither` examples: https://kotlinlang.slack.com/archives/C5UPMM0A0/p1662064718102909?thread_ts=1559561395.141900&cid=C5UPMM0A0

**Comment by Khepu** [comment]
The exact same pattern is followed here:
https://github.com/arrow-kt/arrow/blob/6aa1875a687fb2c1c0e639bdd73be4a05bdfbf7a/arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/Iterable.kt#L1014

This also applies to `Sequence` and `Option`, would changes for all of those be included in the same PR?

Tests for these methods are lacking from what I could tell, would it make sense to create those?

**Comment by raulraja** [comment]
> This also applies to Sequence and Option, would changes for all of those be included in the same PR?
that would be great

> Tests for these methods are lacking from what I could tell, would it make sense to create those?
yes, that'd be great, thanks!

**Comment by nomisRev** [comment]
Hey @Khepu,

> Tests for these methods are lacking from what I could tell, would it make sense to create those?
Yes, that would be greatly appreciated 🙏 There is some tests missing here, and there but we're trying to fill them in over time whenever we have to touch related code.

> This also applies to Sequence and Option, would changes for all of those be included in the same PR?

Yes, you can include `separateValidated` and both methods for `Sequence` as well. I'm not sure this applies to `Option`, since `Option` only holds a single value, but I'm not sure which methods you're referring to.

Also feel free to put it in a separate PR if that is easier for you.
