### ISSUE TITLE
["Request"] ["Docs"] Make docs runnable

### ISSUE THREAD

**Issue by stianste** [arrow-kt/arrow#2828]
# What version are you currently using?
NA

# What would you like to see?
The output of the examples in the docs

I just started reading up on the docs for [Either](https://arrow-kt.io/docs/0.12/apidocs/arrow-core-data/arrow.core/-either/), and was furiously looking for a button or something to run the different examples. In pretty much all the cases it would be really useful to see the output of the different examples, so that its easier to understand what all the different functions do. 

I'll provide a small example; here it would be awesome if it would be possible to see the `println` output of `value` to understand what the output will be. 

![image](https://user-images.githubusercontent.com/14058300/192321028-9962aa89-4d2a-46cd-91e6-77b18e2297e2.png)

**Comment by nomisRev** [comment]
Hey @stianste,

Sadly it's not conveniently possible to make the snippets runnable. In the past we've had this, but it required us running our own Kotlin Playground server with Arrow dependencies available.
Besides hosting costs, we also had various maintenance costs since it regularly required updating.

Since then we've however switched to KotlinX Knit, and we can make add the `text` below and have it verified as tests. Would you consider this a sufficient fix for the same problem?

There are more improvements like this we want to make to the documentation and website in the coming months, so this feedback is great! 🙌

**Comment by raulraja** [comment]
A potential alternative may be to have the knit files compiled to Kotlin JS since arrow is multiplatform and run the examples in the browser. Not sure how complex or feasible this is as I have 0 experience with Kotlin in the browser.

**Comment by nomisRev** [comment]
@raulraja afaik that would only work for uneditable snippets, so the output should be consistent for all (non-parallel) examples. Since we can only _precompile_ to JS, but we cannot bootstrap the Kotlin compiler from JS in the browser afaik to produce editable Kotlin code on the website.

So with this in consideration, I think the easiest step would be to just fully rely on Knit like KotlinX projects do.

**Comment by nomisRev** [comment]
@stianste what do you think about the following? It makes the output visible, without requiring runnable snippets (or a running server to run the snippets).

https://github.com/arrow-kt/arrow/blob/ea0419b7d41ff4f50edda529b97c17e72719433a/arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/Either.kt#L881

The assertions are also verified on CI, so they cannot become outdated. A part of 2.x.x is also to tackle, and heavily improve documentation. So this would be applied to all the documentation in that effort.

**Comment by stianste** [comment]
@nomisRev sorry for a bit late reply, but thank you so much for your answers and enthusiasm 🙏 

In my case I would only need to see the output of the code, in order to understand how it works and learn. So just the stdout would suffice. It would not need to be editable, or run in the browser IMO. It could even be a static part of the documentation or provided as a comment, as long as we can verify that it is actually correct. 

So if your last suggestion here provides that, I would be more than happy!

**Comment by nomisRev** [comment]
Hey @stianste,
This should be taken care on the new website 🥳

All new snippets, and examples now include assertions which are also run on CI as tests so we're 100% sure all examples compile correctly and all output shown is verified on CI to be correct.


<img width="520" alt="Screenshot 2023-04-05 at 07 47 57" src="https://user-images.githubusercontent.com/12424668/229992067-cad1d8ee-7180-492b-8ace-58783f2d0ce4.png">

We're still considering if we can make the snippets editable, and runnable at a later point in time, but this requires constant investment since we need to host a custom server to process the snippets in addition to maintaining a server (with different Kotlin versions & Arrow versions). So we're still evaluating how feasible that will be, but this should cover the discussed use-cases in this issue so I am closing the issue.

Feel free to open a new issue, or comment here again ☺️ Thanks for reporting, and supporting Arrow 🙌
