### ISSUE TITLE
Invariant and Contravariant Functors

### ISSUE THREAD

**Issue by pakoito** [arrow-kt/arrow#283]
https://leanpub.com/fpmortals/read#leanpub-auto-variance

**Comment by pakoito** [comment]
@ersin-ertan is working on Invariant Functors.

**Comment by ersin-ertan** [comment]
@raulraja :eyes: 
- [ ] Ok, almost done - `KleisliFunctorInstance` has:  `fun FF(): Functor<F>` declared within them and the overridden method `fix().map(FF(), f)` uses `FF()`, because `Kleisli` has `map(FF: Functor<F>, f: (A) -> B)` does `Kleisli` and `EitherT, OptionT, Coproduct, StateT, WriterT` require two new function definitions? 

- [ ] Are there are any functions that take `Functor` as the argument, but now that both `Contravariant` and `Functor` extend `Invariant`, will change to take `Invariant` instead?

- [ ] Should `Contra/Invariant` instances be added to `core.dagger` `core.effects` `core.optics`?

- [ ] Some `ApplicativeInstances` extend `ABCFunctorInstance<E>` will these instances also need `ABCContra/InvariantInstance<E>` versions too?

- [ ] In `arrow.mlt` there exists `FunctorFilter`, is a `Contra/Invariant` version need too? If so would anything that extends the new `Contra/InvariantFilter` need specific versions too?

- [ ] Should the `arrow-infographic` update be included on each commit?

**Comment by raulraja** [comment]
> KleisliFunctorInstance has: fun FF(): Functor<F> declared within them and the overridden method fix().map(FF(), f) uses FF(), because Kleisli has map(FF: Functor<F>, f: (A) -> B) does Kleisli and EitherT, OptionT, Coproduct, StateT, WriterT require two new function definitions?

> Are there are any functions that take Functor as the argument, but now that both Contravariant and Functor extend Invariant, will change to take Invariant instead?

I don't think that they require any changes. All those functions use the Covariant Functor. I could not find in cats either the use of Invariant inside those.Unless we have a use case by which to add them I think they are not required

> Should Contra/Invariant instances be added to core.dagger core.effects core.optics?

Yes please, add any new instances to all modules and docs possible where they make sense.

> Some ApplicativeInstances extend ABCFunctorInstance<E> will these instances also need ABCContra/InvariantInstance<E> versions too?

No, but we need `Whatever.invariant()`, etc. in the same way we can do now `Whatever.functor()` where `Whatever` is a data type. If you are using `@instance` for the instances that should be automatic.

> In arrow.mlt there exists FunctorFilter, is a Contra/Invariant version need too? If so would anything that extends the new Contra/InvariantFilter need specific versions too?

I don't believe so and I have not seen those in use there before. Most of them if anything rely on `map` from the Covariant functor.

> Should the arrow-infographic update be included on each commit?
@JorgeCastilloPrz can probably answer this better. I think the idea was to keep changes in the hierarchy trackeable over time visually as well since we plan on automating it down the road that it get's published automatically to the web when there are changes in the hierarchy of type classes.

> Still not sure what to do about:

For that to work we would need to annotate with `@higherkind` the type class interfaces such as that you can have a `ForMonoid` Kind and you can construct a `Invariant<ForMonoid>`. Not long ago we removed the need to annotate type classes with `@typeclass` so maybe the `@higherkind` annotation works and you may be able to annotate `Monoid` as such. We may need to do something similar for Arrow generic in the `Generic` type class to derive type class instances automatically given the ones defined for product types and in that context we are gonna be treating type classes as kinds as wel, so it does not hurt if you try and share what you find there :)

**Comment by ersin-ertan** [comment]
https://github.com/ersin-ertan/arrow/tree/add_typeclass_invariant_contravariant Is feature complete(except for Invariant's monoid instance)
https://github.com/ersin-ertan/arrow/tree/invariant_monoid_instance Branches off of above, [showcasing two ways](https://github.com/ersin-ertan/arrow/blob/invariant_monoid_instance/modules/core/arrow-instances-core/src/main/kotlin/arrow/instances/invariant.kt#L19) to get an Invariant monoid instance for:
`fun <A, B> Kind<ForMonoid, A>.imap(f: (A) -> B, fi: (B) -> A): Kind<ForMonoid, B> =`
- `object : Kind<ForMonoid, B>, Monoid<B>`
- `object : InvariantMonoidInstance<B>`

If `invariant_monoid_instance` is not relevant/needed, I can continue with the pull request for `add_typeclass_invariant_contravariant`

**Comment by pakoito** [comment]
@ersin-ertan now make a Pull Request so we can review the code: https://github.com/arrow-kt/arrow/compare/master...ersin-ertan:add_typeclass_invariant_contravariant?expand=1

**Comment by pakoito** [comment]
It's already in :D
