### ISSUE TITLE
Effect and Either when using context-receiver

### ISSUE THREAD

**Issue by someh2705** [arrow-kt/arrow#2868]
I am a student studying functional programming through Arrow. 

I'm not good at English, so this issues was written through a translator.

```kotlin
suspend fun doSomething(): Either<SomethingFailure, String> = TODO()
```
This function signature shows that it can return `SomethingFailure` and `String` as result values.

```kotlin
suspend fun doSomething(): Effect<SomethingFailure, String> = TODO()
```
Likewise, this function signature shows that it can return `SomethingFailure` and `String` and **Throwable** .

But if you use `context-receiver`, they both have the same function signature, like 
```kotlin
context(EffectScope<SomethingFailure>)
suspend fun doSomething(): String = TODO()
```

Is there any way to differentiate between the two?

For example, how about separating the EffectScope interface into `EitherScope` and inheriting it so that the functions of EffectScope cannot be called from EitherScope?

**Comment by nomisRev** [comment]
Hey @someh2705,

> I'm not good at English, so this issues was written through a translator.

No worries! ☺️ Thank you for taking an interest in Arrow.

`suspend` shows that it can return `Throwable`. So `suspend fun doSomething(): Either<SomethingFailure, String> = TODO()` shows it can result in `Throwable` and  _either_ `SomethingFailure` _or_ `String`.

The second function you shared is typically written _without_ `suspend`:

```kotlin
fun doSomething(): Effect<SomethingFailure, String> = TODO()
```

Since `Effect<E, A>` models `suspend EffectScope<E>.() -> A`, and in 2.x.x (and soon 1.2.0) this even modelled as:

```kotlin
typealias Effect<E, A> = suspend Raise<E>.() -> A
```

Where `Raise` is the _new_ name for `EffectScope`, so `typealias Raise<E> = EffectScope<E>`. So the two functions are _isomorphic_, or model the same program. They both can result in `Throwable` modelled through `suspend`, and `E` or `A` modelled by `Effect` or `Either`. They can also be transformed back-and-forth.

```kotlin
suspend fun example(): Either<SomethingFailure, String> = TODO()
fun example2(): Effect<SomethingFailure, String> = effect { example().bind() }
suspend fun example3(): Either<SomethingFailure, String> = either { example2().bind() }
```

> For example, how about separating the EffectScope interface into EitherScope and inheriting it so that the functions of EffectScope cannot be called from EitherScope?

So making this restriction would actually make interoperability more complex, and moving back-and-forth would be more complex.

So why does `Effect` exist alongside `Either`?

First of all, it will become a simple `typealias Effect<E, A> = suspend Raise<E>.() -> A`, to _easy_ working with lambdas. Which can be useful in some cases. Having to specify `suspend Raise<E>.() -> A` is more cumbersome than `Effect<E, A>` but the real interesting evolution comes with [Kotlin Context Receivers](https://github.com/Kotlin/KEEP/blob/master/proposals/context-receivers.md). More on [my blog](https://nomisrev.github.io/context-receivers/).

Where you can use `Raise` inside of the context.

```kotlin
context(Raise<SomethingFailure>)
suspend fun one(): Int = 1 // Or more complex program that results in `SomethingFailure`

context(Raise<SomethingFailure>)
suspend fun two(): Int = one() + one()
```

Now there is no more need for _bind_ or `Either` and we can use simple functions with regular _returns types_ without wrappers such as `Either` or `Effect`. While still allowing to interact with `Either` based code, which leaves the decision to the users of Arrow on how they want to encode things.

```kotlin
context(Raise<SomethingFailure>)
suspend fun one(): Int = raise(SomethingFailure)

val either: Either<SomethingFailure,  Int> = either { one() }

context(Raise<SomethingFailure>)
suspend fun two(): Int = one() + either.bind()
```

You can find more information on my blog, or by browsing the #arrow channel on KotlinLang. This is now also possible without an account. https://slack-chats.kotlinlang.org/c/arrow

I'm going to close the issue, but feel free to ask any additional follow-up questions. We're also working on new documentation around `Raise`, `Either`, and how they relate to each-other and relate to Kotlin(X) Coroutines. This will be released later this month, or beginning of January.
