### ISSUE TITLE
alpha in maven release

### ISSUE THREAD

**Issue by gabrieljones** [arrow-kt/arrow#2883]
Why are `alpha` and `rc` versions showing up in the `maven-metadata.xml` `<release>` tag?

https://repo1.maven.org/maven2/io/arrow-kt/arrow-core/maven-metadata.xml

**Comment by gabrieljones** [comment]
It also looks like https://github.com/arrow-kt/arrow/releases/tag/1.1.4 did not get published to maven.

**Comment by nomisRev** [comment]
hey @gabrieljones,

Thanks for opening this issue! We have 1.1.4 still in sona, and are preparing 1.1.5 to be both released next week.
Due to the holidays this got a bit stretched out..

Next week this should be in order, you'll also see the version appear in the Github releases page when they officially get released.

**Comment by gabrieljones** [comment]
@nomisRev Do you happen to have a link to a commit where this was fixed?

**Comment by gabrieljones** [comment]
@nomisRev https://repo1.maven.org/maven2/io/arrow-kt/arrow-core/maven-metadata.xml is currently showing `1.1.5-alpha.4` in the `release` tag.  This should be `1.1.3` according to all the versions currently showing in the `maven-metadata.xml`. Once `1.1.4` is published then it should be `1.1.4`.

**Comment by gabrieljones** [comment]
@nomisRev Please reopen this issue if it has not been fixed yet.
