### ISSUE TITLE
["Request"] Error mapper utility

### ISSUE THREAD

**Issue by CLOVIS-AI** [arrow-kt/arrow#3053]
Since using Arrow, I tend to have a sealed class hierarchy of failures for each computation my app may execute. It is common for computations to execute other computations as a step.

For example, let's say we have some kind of parsing operation:
```kotlin
sealed class ParsingError {
    object ErrorReason1 : ParsingError()
    object ErrorReason2 : ParsingError()
}

fun parse(…): Either<ParsingError, ParsingResult> = …
```
And we have another operation, of which parsing is one of the steps:
```kotlin
sealed class ParentError {
    object ErrorReason1 : ParentError()

    // Encapsulate the child error
    data class ParsingError(val error: ParsingError) : ParentError()
}

fun parent(…): Either<ParentError, ParentResult> = either {
    ensure(…) { ParentError.ErrorReason1 }
    
    // Here, how should we call `parsing(…)` to propagate errors correctly?
}
```

### Current solution: mapLeft

```kotlin
parsing(…)
    .mapLeft(ParentError::ParsingError)
    .bind()
```

This is easy to read, but it's quite verbose, especially when context receivers will remove all other `.bind()` calls. It also only works if the parsing operation returns `Either`, or it requires one more conversion function.

### Current solution: recover

```kotlin
recover({ parsing(…).bind() }) { raise(ParentError.ParsingError(it)) }
```

Again, it's very bulky. The `recover` DSL is quite powerful, but this is such a simple case that it's mostly boilerplate.

### Proposed new feature: mapErrors

To simplify this case, it would be nice to provide a specific function for this:
```kotlin
mapErrors(ParentError::ParsingError) {
    parsing(…).bind()
}
```

> The discussion [started on Slack](https://kotlinlang.slack.com/archives/C5UPMM0A0/p1684066366615369).

**Comment by kyay10** [comment]
I'd be more than happy to roll a PR for this!

Does the `transform` lambda need to have a `Raise<Error>` receiver though? It'll already be accessible within the calling context (because withError has the same exact receiver) and it *prevents* function references that simply transform the error. It does technically allow function references that specifically also need a `Raise<Error>` and transform the error, but who would write functions like that when you can simply early-return with the `Error` value? Also, let's imagine we have such a function `fun Raise<MyError>.foo(error: MyError2): MyError`. You can easily obtain a reference to `foo` in the form `(MyError2) -> MyError` (note the lack of receiver) by doing `this@either::foo`. The signature `Raise<X>.(Y) -> X` is practically a function that returns `Either<X, X>`, which really doesn't make sense IMO, and it has no syntactic advantages at the call site.

Also, I saw that there's a DslContext annotation `@RaiseDsl`. Might that impact or prevent raising an `Error` inside the `block` (which has a `Raise<Error2>`)? If it does prevent it, maybe we should reconsider the DslContext annotation? If not, this function would need to have `block: context(Error, Error2) () -> A`

**Comment by nomisRev** [comment]
> I'd be more than happy to roll a PR for this!

That'd be great!

> Does the transform lambda need to have a Raise<Error> receiver though?

You're right, it absolutely doesn't. Since it can only occur within the context of `Raise<Error>` it's completely redundant.

> Also, I saw that there's a DslContext annotation @RaiseDsl. Might that impact or prevent raising an Error inside the block (which has a Raise<Error2>)? If it does prevent it, maybe we should reconsider the DslContext annotation? If not, this function would need to have block: context(Error, Error2) () -> A

No, this is not an issue. It's currently not being leveraged in such a way that it prevents nested scoping.

**Comment by CLOVIS-AI** [comment]
Thanks for this :) Please do @ me on the PR, I'm interested in learning more about the internal Arrow structures and how to contribute.
