### ISSUE TITLE
["Request"] Ease NonEmptyCollection methods usage calling suspend

### ISSUE THREAD

**Issue by christophejan** [arrow-kt/arrow#3116]
### What version are you currently using?

1.2.0

### What would you like to see?

Currently, the following `mapIndexedOnNonEmptyList` method get a `Suspension functions can be called only within coroutine body` compilation error, but not `mapIndexedOnStandardCollection ` :
```
suspend fun mySuspendFunction(index: Int, value: Int): Any = TODO()

suspend fun mapIndexedOnNonEmptyList() =
    nonEmptyListOf(1, 3, 7).mapIndexed { index: Int, value: Int -> mySuspendFunction(index, value) }

suspend fun mapIndexedOnStandardCollection() =
    listOf(1, 3, 7).mapIndexed { index: Int, value: Int -> mySuspendFunction(index, value) }
```

I would like to be able to use `NonEmptyCollection` methods in a suspend method definition the same way you can on standard collections.

(note that the standard collection behavior is due to **`inline`** method definition of `Iterable<T>.mapIndexed`)

### Why?

I think that it would ease `NonEmptyCollection` usage (to avoid custom extensions or to avoid switching back on standard collections).

**Comment by serras** [comment]
The problem here is that `NonEmptyCollection` defines `map` and friends as member methods. We could define them as extension functions, but this has two drawbacks:
1. We cannot provide "direct" implementations for things like `NonEmptyList`,
2. We would break source compatibility, since now users would need to import `map` explicitly.

What do you think? Summoning also @nomisRev @raulraja @franciscodr to the conversation.

**Comment by christophejan** [comment]
Thank You @serras @nomisRev
