### ISSUE TITLE
shift signature Bug in EagerEffectScope

### ISSUE THREAD

**Issue by codymikol** [arrow-kt/arrow#3298]
Looking at the signature in EagerEffectScope I see

```kotlin
  /** Short-circuit the [EagerEffect] computation with value [R].
   *
   * ```kotlin
   * import arrow.core.continuations.eagerEffect
   * import io.kotest.assertions.fail
   * import io.kotest.matchers.shouldBe
   *
   * fun main() {
   *   eagerEffect<String, Int> {
   *     shift("SHIFT ME")
   *   }.fold({ it shouldBe "SHIFT ME" }, { fail("Computation never finishes") })
   * }
   * ```
   * <!--- KNIT example-eager-effect-scope-01.kt -->
   */
  public suspend fun <B> shift(r: R): B
```

shouldn't shift have a parameter type that is on the left path `L` and a `Unit` return type?

```kotlin
public suspend fun <L> shift(r: L):  Unit
```

That would be in line with the example

Currently you can shift with any type because EagerEffectScope does not know about the left generic

**Comment by nomisRev** [comment]
Hey @codymikol,

`R` is here already the left (`L`) side, coming from `fun <R, A> eagerEffect(block: Raise<R>.() -> A): EagerEffect<R, A>`.

The reason it introduces a new generic `B`, and returns `B` is because it's actually returning `Nothing`. So the `B` here is artificial. In Arrow 2.0 the signature changes to `public suspend fun shift(r: R):  Nothing` where `R` is the error channel of `EagerEffect`.

**Comment by codymikol** [comment]
I understand now, thanks
