### ISSUE TITLE
Stack safety for Schedule (resilience)

### ISSUE THREAD

**Issue by c11v** [arrow-kt/arrow#3336]
I was reading through the implementation of [Schedule](https://github.com/arrow-kt/arrow/blob/main/arrow-libs/resilience/arrow-resilience/src/commonMain/kotlin/arrow/resilience/Schedule.kt). I'm trying to figure out why using recursion without tail call optimization is stack safe. 

For example, the [spaced](https://github.com/arrow-kt/arrow/blob/main/arrow-libs/resilience/arrow-resilience/src/commonMain/kotlin/arrow/resilience/Schedule.kt#L263-L266) implementation uses a `loop` recursive function in its implementation. How can this be used for a large number of invocations without exhausting the stack?

**Comment by serras** [comment]
In theory this should not be a problem for the following reason: at any point there's more than one instance in memory. When we write

```kotlin
Continue(input, duration) { loop(input + 1) }
```

we have only `Continue` + a function in memory. It's only when we execute the `Schedule` that we obtain the function inside of it. This is the reason why in the [implementation of `retry`](https://github.com/arrow-kt/arrow/blob/main/arrow-libs/resilience/arrow-resilience/src/commonMain/kotlin/arrow/resilience/Schedule.kt#L425) we do use a loop instead of recursion, because that's the place where stack overflow may actually happen if you're not careful.

**Comment by nomisRev** [comment]
Pretty much this what @serras said, because the _execution_ occurs in a loop _execution_ becomes stack-safe.

> This is the reason why in the [implementation of retry](https://github.com/arrow-kt/arrow/blob/main/arrow-libs/resilience/arrow-resilience/src/commonMain/kotlin/arrow/resilience/Schedule.kt#L425) we do use a loop instead of recursion, because that's the place where stack overflow may actually happen if you're not careful.

However, when building a recursive schedule things might become stack unsafe but these scenarios are very rare as you can see in the example this is just a badly implemented `Schedule.forever()`.

```kotlin
public fun <A> infinite(): Schedule<A, Unit> =
  Schedule.recurs<A>(1)
    .andThen(infinite()) // <-- unsafe recursion
    .map { }
```

This could probably be rewritten to `fold`, which then would be stack-safe but this this example wouldn't make sense since the `infinite()` function never returns.

I am closing this ticket because I hope this answers your questions. If you have a snippet that fails, we can come up with a solution or fix together ☺️ If you have any other questions feel free to ask here, or open a new ticket as well!
