### ISSUE TITLE
[optics] Rethink generating inline functions

### ISSUE THREAD

**Issue by sindrenm** [arrow-kt/arrow#3500]
Most (if not all) of the generated functions from arrow-optics, are seemingly `inline` for no reason. The compiler complains about this with the following message:

> Expected performance impact from inlining is insignificant. Inlining works best for functions with parameters of function types.

As you can imagine, this quickly gets quite noisy:

![image](https://github.com/user-attachments/assets/c7ce1cdb-1c42-4e44-92c7-29c566cacac2)

Is there a specific reason why these are generated as inline, or can this be changed?

**Comment by serras** [comment]
The reasoning here is that if we inline the use of the optics, we can get performance very close to direct access to the data itself. That is, we would like `Person.name.firstName.get(person)` not to cost more than `person.name.firstName`.

However, whether we achieve that is, of course, arguable. Even more so because the JVM is able to remove very small function calls itself.

**Comment by sindrenm** [comment]
Indeed, but as the compiler suggests, the performance gains here are insignificant.

**Comment by sindrenm** [comment]
Thanks! :tada:
