### ISSUE TITLE
Cannot find 2.0 changelist

### ISSUE THREAD

**Issue by mgroth0** [arrow-kt/arrow#3542]
The recent 2.0 release points to the website, but not to a specific page. I could not find the changelist.

**Comment by G00fY2** [comment]
Also the readme should probably be updated: https://github.com/arrow-kt/arrow?tab=readme-ov-file#arrow-20

**Comment by sindrenm** [comment]
It's also not yet available on Maven Central, so my guess is that it isn't fully released yet.

![image](https://github.com/user-attachments/assets/8ac56dc5-770a-4ee4-89b2-d772440a2a16)

As for the changelist, IIRC, the team made an effort to make 1.2.4 as similar as possible API-wise to the upcoming 2.0.0 release, but you can expect some breaking changes like removed deprecated APIs.

**Comment by serras** [comment]
This is the [release announcement](https://arrow-kt.io/community/blog/2024/12/05/arrow-2-0/).

Unfortunately there's a big of chicken-and-egg problem here, because we can only get the URL for the blog post once it's published, but on the other hand we don't want to publish the blog post until the artifacts are out.
