### ISSUE TITLE
Provide support to bypass the ScriptEngine and just compile with `kotlin:ank:compile`

### ISSUE THREAD

**Issue by raulraja** [arrow-kt/arrow#472]

**Comment by nomisRev** [comment]
This might be easy with [Fluid compiler](https://github.com/fluidsonic/fluid-compiler), it also has support for running kapt from code.

**Comment by AlexITC** [comment]
We do need this one too, is there any plans for it?

**Comment by nomisRev** [comment]
Hey @AlexITC,

There are currently not any active plans to work on this. With the recent changes in Dokka with [plugins](https://kotlin.github.io/dokka/1.4.30/developer_guide/introduction/) we were hoping to migrate Ank or its functionality to a plugin. Which might change the focus a little bit to focus on project documentation rather than markdown-style evaluation which is also already covered by [KotlinX-Knit](https://github.com/Kotlin/kotlinx-knit).

Are you currently using Ank in your project? And what is your use-case for `kotlin:ank:compile`?

**Comment by AlexITC** [comment]
We are using ank to type-check kotlin code snippets in our docs, there are some examples that perform network calls which won't work in our CI that builds our docs website, hence, making sure that those examples compile without executing them is ideal.

**Comment by raulraja** [comment]
@AlexITC Development of Ank has been discontinued in Arrow in favor of Knit in #2634 #2584. Knit covers your use case of just compiling code snippets without executing them. I'll close this issue, but If you still rely on Ank and need help migrating feel free to swing by our slack channel in the [Kotlin](https://slack.kotlinlang.org/) slack where we can help out on how to migrate to knit.

**Comment by AlexITC** [comment]
Thanks! I'll check because I don't even remember if we still use Ank.
