### ISSUE TITLE
Add operator overloads to Syntax classes

### ISSUE THREAD

**Issue by pakoito** [arrow-kt/arrow#729]
Syntax modules enable functions that weren't possible before. In this case we could define Kotlin's operators:
* plus() in SemiGroup
* equals() in Eq
* compareTo() in Order

And any others in here: https://kotlinlang.org/docs/reference/operator-overloading.html

**Comment by raosuj** [comment]
can i take this ?

**Comment by pakoito** [comment]
Sure! Go ahead, and ask any questions on the gitter channel.

**Comment by Mishkun** [comment]
Seems no progress on issue... :hmm:
Eq cannot be provided with equals() op, because every class have equals() member function, which shadows the extension op.
Semigroup was already provided with `+` syntax in #768 .
Order can be provied with compareTo() easily, can submit a PR.
Haven't come up with other useful operators yet
