### ISSUE TITLE
Destructuring Option instances

### ISSUE THREAD

**Issue by nhaarman** [arrow-kt/arrow#897]
The `Option` class currently does not define a `component1()` function to be able to destructure it.
 
A common use case is wrapping a nullable type in an `Option` because RxJava does not allow `null` values in its streams:

```kotlin
.subscribe { myOption : Option<T> ->
  value = myOption.orNull()
}
```

Instead, when destructuring:

```kotlin
.subscribe { (myValue : T?) ->
  value = myValue
}
```

**Comment by pakoito** [comment]
Some implements `component1()`, so you need to have it resolved as a `Some` first.

**Comment by pakoito** [comment]
Meanwhile, have you tried defining it as an extension function instead?

**Comment by nhaarman** [comment]
>  If what you want is for Option#component1() to behave like orNull()

That was my intention, yes. I didn't see `Some.component1()`, so that may cause some conflicts.

> Meanwhile, have you tried defining it as an extension function instead?

Yes, that works, but requires an explicit import (e.g. `import com.myapp.util.component1()`). Intellij does not autosuggest the import.

**Comment by JorgeCastilloPrz** [comment]
Koptional implemented this. I suggest to take a look at their discussions and code of the PR.
https://github.com/gojuno/koptional/pull/20

**Comment by pakoito** [comment]
KOptional took a month to reluctantly accept it, and it's the only operator in the library :/

>I didn't see Some.component1(), so that may cause some conflicts.

The `it.orNull()` option isn't really that long to write, and the behavior isn't implicit on whether you wrap a variable in parenthesis or not. 

In the past we also had the chance to override operators instead of using functions like `extensions` or `bind`, and we went for the longer function version to keep the original intended use of operators. I'd err in the side of a couple more characters and call the function here too.

**Comment by nhaarman** [comment]
Sounds reasonable to me. :+1:
